Repository department-of-veterans-affairs/LEAF, pull requests merged in 2021-06, with the labels that each got.

#1394 QA-RC: LEAF-2239 - Resolved By Cleanup
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature

#1393 QA-RC: LEAF-2267 - Fix IE User Access Group Search Text
  libs/css/leaf.css
  libs/sass/leaf.scss
Labels: bug

#1392 QA-RC: LEAF-882 - Portal Nexus Link Focus Fix
  LEAF_Request_Portal/templates/menu.tpl
Labels: bug

#1395 QA-RC: Workflow Maintenance
  .github/workflows/pullrequests.yml
  CODEOWNERS
Labels: enhancement

#1396 QA-RC: LEAF-1585 - OR Logic
  LEAF_Request_Portal/form.php
Labels: feature

#1397 QA-RC: LEAF-1585: - OR Logic Change op to gate
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/view_search.tpl
  libs/js/LEAF/formQuery.js
  libs/js/LEAF/formSearch.js
  libs/jsapi/portal/model/FormQuery.js
Labels: feature

#1400 QA-RC: LEAF-1585 - OR Logic Fixes
  LEAF_Request_Portal/form.php
Labels: bug
