Repository department-of-veterans-affairs/LEAF, pull requests merged in 2021-07, with the labels that each got.

#1403 QA-RC: LEAF-1585 - Backwards Compatibility for importQuery
  LEAF_Request_Portal/js/formQuery.js
  libs/js/LEAF/formQuery.js
  libs/jsapi/portal/model/FormQuery.js
Labels: enhancement

#1405 LEAF-2138 - Last Workflow Change in Report Builder
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature

#1408 QA: LEAF-2326 - Restrict Service Groups to One Position
  LEAF_Nexus/templates/view_group.tpl
  LEAF_Nexus/templates/view_position.tpl
Labels: bug

#1413 QA-RC: DB_Upgrade for Sprint 9-10
  LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2021041900-2021062800.sql
Labels: database

#1417 QA-Hotfix: LEAF-2375 - Email.php Fatal Error Typo
  .github/workflows/lint_me.yml
  LEAF_Request_Portal/Email.php
Labels: hotfix

#1418 QA-Hotfix: LEAF-2378 - Emails Not Sending to Next Approver
  LEAF_Request_Portal/Email.php
Labels: bug, hotfix

#1426 Hotfix: LEAF-2398 - Handle Multiple Email Dependencies
  LEAF_Request_Portal/Email.php
Labels: bug, hotfix

#1430 Bugfix: LEAF-2357 - Added name check for Group Designated
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Labels: bug

#1429 Hotfix: LEAF-2394 - Mass_Action Fix
  LEAF_Request_Portal/js/pages/mass_action.js
Labels: bug, hotfix

#1428 Feature: LEAF-2194 - Form Archival
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/view_disabled_fields.tpl
  LEAF_Request_Portal/api/controllers/FormEditorController.php
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/sources/FormEditor.php
Labels: feature

#1427 Workflow: Change PR Notifications to Master Branch
  .github/workflows/pullrequests.yml
Labels: enhancement
