Repository department-of-veterans-affairs/LEAF, pull requests merged in 2021-08, with the labels that each got.

#1432 Bugfix: LEAF-2359 - Workflow Hanging up on Applying Action
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/js/workflow.js
Labels: bug

#1439 hotfix: LEAF-2416 fix export button, verbiage
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, hotfix

#1440 Bugfix: LEAF-1936-file attachment fields are not reflecting protected status
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: bug

#1438 Feature: LEAF-2413 - EmpMembership Main TPL Var
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/report.php
Labels: feature

#1437 FEATURE: LEAF-2405 - Dedicated Session Timeout Page
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/session_expire.php
  LEAF_Request_Portal/templates/view_session_expire.tpl
Labels: feature

#1435 Rc/210801/sprint 12 c1/2359 2335
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: release

#1441 hotfix: LEAF-2424 fix title input
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, hotfix

#1448 propagate change events
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#1447 Bugfix: LEAF-2428 - Mass Action Search Fix
  LEAF_Request_Portal/js/pages/mass_action.js
  LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
Labels: bug, rc-ready

#1446 FEATURE: LEAF-2374 - Site Caching
  LEAF_Request_Portal/db_mysql.php
  docker/docker-compose.yml
  docker/env_files/caching.env
  docs/Development.md
Labels: feature, rc-ready

#1442 Bugfix: LEAF-1987 - Currency/Validation/Required checks and Auto-Scroll to Input fields
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/parallelProcessing.js
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#1454 Feature LEAF 883-header color options (new)
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature, rc-ready

#1452 Remove condition when querying non-empty string
  LEAF_Request_Portal/form.php
Labels: bug, rc-ready

#1450 Bugfix: LEAF-2356 - Date Field Validation
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#1456 LEAF-883 most comparison changes back to == or !=
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature

#1458 hotfix LEAF 2455: revert variable name
  LEAF_Request_Portal/js/parallelProcessing.js
Labels: bug

#1451 Rc/210813/sprint 13 c1/1987 2374 2428 2431 dependa
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/db_mysql.php
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/pages/mass_action.js
  LEAF_Request_Portal/js/parallelProcessing.js
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  docker/docker-compose.yml
  docker/env_files/caching.env
  docs/Development.md
  test/js/yarn.lock
Labels: release, on-prod

#1459 Feature LEAF 883 header color options new
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, feature

#1457 Rc/210820/sprint 13 c 2/883 2356 2431
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: on-prod
