Repository department-of-veterans-affairs/LEAF, pull requests merged in 2021-09, with the labels that each got.

#1461 Rc/210903/sprint 14 c 1/2471
  LEAF_Nexus/auth_cookie/index.php
  LEAF_Nexus/auth_domain/index.php
  LEAF_Nexus/auth_token/index.php
  LEAF_Nexus/index.php
  LEAF_Nexus/login/index.php
  LEAF_Nexus/report.php
  LEAF_Nexus/sources/Login.php
  LEAF_Nexus/sources/System.php
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/Login.php
  LEAF_Request_Portal/ajaxIframe.php
  LEAF_Request_Portal/auth_cookie/index.php
  LEAF_Request_Portal/auth_domain/Login.php
  LEAF_Request_Portal/auth_domain/index.php
  LEAF_Request_Portal/auth_token/index.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/login/index.php
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/Shortener.php
  LEAF_Request_Portal/sources/Site.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/Telemetry.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
  libs/qrcode/index.php
Labels: release, on-prod, on-preprod

#1468 Feature: LEAF-2475 - import grid splitter to report builder
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature, rc-ready

#1467 LEAF-2479 sticky menus, overflow fix
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement, rc-ready

#1463 Bugfix: LEAF-2473 - New Row logic update
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, rc-ready

#1462 Feature: LEAF-2441 - expand report builder for grids
  LEAF_Request_Portal/css/report.css
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: enhancement, feature, rc-ready

#1470 LEAF-2475 - import grid splitter to report builder
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature

#1471 LEAF-2475: import grid splitter to admin panel
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: feature

#1474 Bugfix: LEAF-2504 - Quadrad/Pentad Email Notification
  LEAF_Request_Portal/Email.php
Labels: hotfix, rc-ready

#1477 LEAF 2468-css for report builder display
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: enhancement, rc-ready

#1476 bug: LEAF-2506 fix required currency bug
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#1465 Database: LEAF-2193 - Upgrade DB for Custom Events
  LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2021062800-2021091600.sql
Labels: database, rc-ready

#1464 Feature: LEAF-2193 - Custom Email Events
  LEAF_Request_Portal/Email.php
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/admin/css/mod_workflow.css
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/email/base_templates/LEAF_template_body.tpl
  LEAF_Request_Portal/templates/email/base_templates/LEAF_template_subject.tpl
  libs/logger/formatters/loggableTypes.php
  libs/logger/formatters/workflowFormatter.php
Labels: feature, rc-ready

#1481 Feature: LEAF-2193 - Verbiage Changes
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: feature

#1482 DB: LEAF-2193 - DB Syntax Fix
  LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2021062800-2021091600.sql
Labels: database

#1483 Feature: LEAF-2193 - Click Dialog Hiding Fix
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: feature

#1484 DB: LEAF-2193 - DB Workaround Existing FK
  LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2021062800-2021091600.sql
Labels: database

#1485 Hotfix: LEAF-2524 - Form Overlapped Fix
  LEAF_Request_Portal/css/style.css
Labels: bug, hotfix

#1487 hotfix LEAF-2527 grid hotfix
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, hotfix

#1489 Bugfix: LEAF-2529 - File Upload Try Again Button
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/templates/file_form_error.tpl
Labels: bug

#1493 DB: LEAF-2193 - SQL Fix
  LEAF_Request_Portal/utils/db_upgrade/Update_RMC_DB_2021062800-2021091600.sql
Labels: database
