Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-08, with the labels that each got.

#1619 Leaf 2999 reportbuilder: visual display of archived fields
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#1623 Rc/2022 08 04/sprint 36 c1
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready, on-prod, on-preprod

#1625 LEAF-3002: Revert Timeline Changes
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: revert

#1622 LEAF-2975 Queries WHERE IN are null/empty
  LEAF_Request_Portal/form.php
Labels: bug, rc-ready

#1624 LEAF 2992 JS utility update, and some tpl cleanup
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/mod_conditions_editor.tpl
  LEAF_Request_Portal/admin/templates/site_elements/generic_dialog.tpl
  LEAF_Request_Portal/css/report.css
  LEAF_Request_Portal/templates/view_reports.tpl
  libs/js/LEAF/XSSHelpers.js
Labels: rc-ready

#1620 LEAF 3004, IFTHEN: handle conditions with encoded characters
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: rc-ready

#1614 LEAF 2833 'Choicesjs' plugin for multiselect questions
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/js/formPrint.js
  LEAF_Request_Portal/js/gridInput.js
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  libs/js/choicesjs/choices.min.css
  libs/js/choicesjs/choices.min.js
Labels: enhancement, rc-ready, on-prod

#1599 LEAF 2920 - Create a process to run a script on an interval between t…
  scripts/readme.md
  scripts/refreshOrgchartEmployees.php
  scripts/scheduled-task-commands/refreshOrgchartEmployees.sh
  scripts/scheduled-task-commands/test.php
  scripts/scheduled-task-commands/test.sh
  scripts/timebracketcmd.php
  scripts/timebracketcmdtest.php
Labels: feature

#1643 LEAF-3087: Delete Route Event in History does not return message
  libs/logger/formatters/workflowFormatter.php
  libs/logger/logFormatter.php
Labels: bug
