Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-09, with the labels that each got.

#1646 Bug leaf 3091: ifthen php8 fallout
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: hotfix

#1637 Clarify this is for a load indicator
  LEAF_Request_Portal/js/dialogController.js
Labels: rc-ready

#1636 Enable post-render customizations
  LEAF_Request_Portal/js/workflow.js
Labels: rc-ready

#1627 Speed up admin/?a=mod_groups page load
  LEAF_Request_Portal/admin/Group.php
Labels: rc-ready

#1626 Update sites in parallel
  LEAF_Request_Portal/templates/reports/LEAF_National_Distribution.tpl
Labels: rc-ready

#1657 LEAF-3098 Report builder optimization
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: on-prod, on-preprod

#1655 Rc/2022 09 08/php8 fixs and cleanup
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/templates/reports/LEAF_National_Distribution.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: hotfix, on-prod, on-preprod

#1661 LEAF-3103: Hotfix: Left out timestamp
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: hotfix, on-prod, on-preprod

#1649 Bug leaf 3066 xsshelpers
  libs/php-commons/XSSHelpers.php
Labels: bug, rc-ready

#1653 Prevent required field bypass (workflow indicator)
  LEAF_Request_Portal/js/workflow.js
Labels: hotfix

#1652 These need to be ints
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: hotfix

#1647 Bug leaf 3061 form editor fixes v2p0
  LEAF_Request_Portal/admin/css/mod_form.css
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
Labels: bug, rc-ready

#1660 leaf-3094 nexus nightly script slowly runs
  LEAF_Nexus/db_mysql.php
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: enhancement, feature, rc-ready

#1659 LEAF-3100 Remove client-side cache workaround
  LEAF_Request_Portal/js/formQuery.js
Labels: enhancement, rc-ready

#1658 LEAF-2911: Syncservices Employee Synchronization Fix
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/scripts/VAMC_directory_maintenance2_AD.php
  LEAF_Request_Portal/sources/System.php
Labels: bug, With QA

#1664 leaf 3069 handle parent archive
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: bug, With QA

#1673 LEAF-3128 Batch Insert Data Sanitization
  LEAF_Nexus/db_mysql.php
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: bug, hotfix

#1662 LEAF-2907 Rework
  .gitignore
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: bug, rc-ready
