Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-06, with the labels that each got.

#1568 LEAF-2877: Hotfix for Employee Search
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/NationalEmployee.php
Labels: bug, hotfix, rc-ready, on-prod, on-preprod

#1577 LEAF 2882 add vue (v3.2.33) to libs
  libs/js/vue3/vue.global.prod.js
Labels: dependencies, With QA

#1574 Styles/leaf 2121 2846 2800
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/css/style.css
  libs/css/leaf.css
  libs/sass/leaf-nav-960.scss
Labels: enhancement, With QA

#1576 LEAF-2874: Employee Selector formatting fix
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
Labels: bug, With QA

#1573 LEAF 2879 handle empty unsaved 'checkboxes' values
  LEAF_Request_Portal/js/formPrint.js
Labels: bug, With QA

#1572 LEAF-2828: 'Add to Nexus' button in RP groups
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
Labels: enhancement, With QA

#1578 Rc/2022 06 06/sprint 31 c1
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/js/formPrint.js
  libs/js/vue3/vue.global.prod.js
Labels: release, on-prod, on-preprod

#1580 LEAF-2121,2846,2800: Styles
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/css/style.css
  libs/css/leaf.css
  libs/sass/leaf-nav-960.scss
Labels: enhancement, rc-ready

#1584 Rc/2022 06 13/sprint 32 c1
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/css/style.css
  libs/css/leaf.css
  libs/sass/leaf-nav-960.scss
Labels: release, on-prod, on-preprod

#1586 LEAF-2912: File Upload Directory Creation Fix
  LEAF_Nexus/sources/Data.php
  LEAF_Request_Portal/form.php
Labels: bug, hotfix, on-prod

#1588 LEAF-2919 improve initial form selection display
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/templates/initial_form.tpl
Labels: rc-ready

#1587 LEAF-2915: KILL CONNECTION_ID() line is causing warnings
  LEAF_Nexus/db_mysql.php
  LEAF_Request_Portal/db_mysql.php
Labels: bug, rc-ready

#1583 LEAF-2908: Sync Services Offset Errors
  LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
Labels: bug, rc-ready

#1589 LEAF 2354 Wrap certain non-date format patterns in quotes
  LEAF_Request_Portal/js/formGrid.js
Labels: rc-ready
