Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-11, with the labels that each got.

#1701 Rc/2022 10 27/sprint 41 c1
  LEAF_Nexus/admin/templates/main.tpl
  LEAF_Nexus/css/printer.css
  LEAF_Nexus/css/style.css
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/js/nationalEmployeeSelector.js
  LEAF_Nexus/js/positionSelector.js
  LEAF_Nexus/templates/main.tpl
  LEAF_Request_Portal/css/printer.css
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formPrint.js
  LEAF_Request_Portal/js/gridInput.js
  LEAF_Request_Portal/templates/file_form.tpl
  LEAF_Request_Portal/templates/file_image_form.tpl
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/initial_form.tpl
  LEAF_Request_Portal/templates/main.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: release, on-prod, on-preprod

#1703 fix negative indicatorID conflict
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, on-prod, on-preprod

#1706 Leaf-3209 annomolies with sync services
  LEAF_Request_Portal/scripts/old_sync_services.php
  LEAF_Request_Portal/sources/System.php
Labels: bug, rc-ready

#1707 LEAF-3215: implement 508 guidance on sans-serif fonts
  LEAF_Nexus/css/style.css
  LEAF_Request_Portal/css/style.css
Labels: rc-ready

#1698 LEAF 3151 server side progress check for conditional questions
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: rc-ready

#1711 Rc/2022 11 03/sprint 41 c2
  LEAF_Nexus/css/style.css
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: on-prod, on-preprod

#1704 LEAF-3197 modified how files get deleted
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#1700 LEAF-2452 - copy existing record by
  LEAF_Request_Portal/templates/print_form.tpl
Labels: feature, rc-ready

#1720 LEAF-3247: Email Fixes for Docker
  docker/.env
  docker/docker-compose.yml
  docker/php/leaf_monlith.dockerfile
  docker/php/ssmtp/revaliases
  docker/php/ssmtp/ssmtp.conf
Labels: bug, enhancement

#1721 LEAF-2452 copy existing record by
  LEAF_Request_Portal/form.php
Labels: bug

#1717 LEAF- 3204 jquery library version updates
  libs/js/jquery/css/ui-lightness/images/animated-overlay.gif
  libs/js/jquery/css/ui-lightness/images/ui-bg_diagonals-thick_18_b81900_40x40.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_diagonals-thick_20_666666_40x40.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_flat_10_000000_40x100.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_glass_100_f6f6f6_1x400.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_glass_100_fdf5ce_1x400.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_glass_65_ffffff_1x400.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_gloss-wave_35_f6a828_500x100.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
  libs/js/jquery/css/ui-lightness/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
  libs/js/jquery/css/ui-lightness/images/ui-icons_222222_256x240.png
  libs/js/jquery/css/ui-lightness/images/ui-icons_228ef1_256x240.png
  libs/js/jquery/css/ui-lightness/images/ui-icons_ef8c08_256x240.png
  libs/js/jquery/css/ui-lightness/images/ui-icons_ffd27a_256x240.png
  libs/js/jquery/css/ui-lightness/images/ui-icons_ffffff_256x240.png
  libs/js/jquery/css/ui-lightness/jquery-ui.custom.css
  libs/js/jquery/css/ui-lightness/jquery-ui.custom.min.css
  libs/js/jquery/jquery-ui.custom.min.js
  libs/js/jquery/jquery.js
  libs/js/jquery/jquery.min.js
Labels: bug, rc-ready

#1708 Leaf-3213 modification to notes system
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement, rc-ready

#1713 LEAF-3231 Update orgchart_* widget customization
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#1709 Leaf 3221/3210 stop removal of locally managed and dealing with unexpected data
  LEAF_Nexus/sources/Group.php
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
Labels: bug, rc-ready

#1719 LEAF 3246 conditional question requirement handling in form fields
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: bug, rc-ready

#1722 LEAF-3253 Fix array merge error
  LEAF_Request_Portal/form.php
Labels: rc-ready

#1726 LEAF-3223: Inactive User List
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/admin/css/mod_groups.css
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
Labels: enhancement, With QA

#1760 Leaf-3289 undoing Leaf-3253
  LEAF_Nexus/db_mysql.php
  LEAF_Request_Portal/db_mysql.php
Labels: revert

#1761 Rc/2022 11 21/sprint 43 non demoed updates
  LEAF_Nexus/db_mysql.php
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/UserActivity.php
  LEAF_Request_Portal/db_mysql.php
  LEAF_Request_Portal/templates/view_logout.tpl
  libs/js/LEAF/sessionAnnounce.js
  libs/js/LEAF/sessionTimeout.js
Labels: on-prod

#1712 LEAF 3119 - automated email notifications
  LEAF_Request_Portal/Email.php
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022050300-2022110300.sql
  scripts/automatedEmailReminder.php
  scripts/scheduled-task-commands/automatedEmailReminder.php
Labels: feature, With QA
