Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-10, with the labels that each got.

#1677 Rc/2022 09 29/sprint 39 c1
  .gitignore
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  LEAF_Request_Portal/templates/view_search.tpl
Labels: on-prod

#1678 LEAF-3128: Hotfix Array Keys Issue
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: hotfix

#1675 LEAF Installation Documentation for 2-0
  docs/InstallationConfiguration.md
Labels: feature, rc-ready, With QA

#1674 LEAF-3129 Add missing script
  LEAF_Request_Portal/admin/templates/main.tpl
Labels: rc-ready

#1684 LEAF-3157 setAttribute
  LEAF_Request_Portal/db_mysql.php
Labels: bug, hotfix, on-prod

#1683 LEAF 3139. 508 issues
  LEAF_Nexus/css/style.css
  LEAF_Nexus/templates/menu.tpl
  LEAF_Nexus/templates/view_homepage.tpl
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/admin/templates/main.tpl
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/initial_form.tpl
  LEAF_Request_Portal/templates/main.tpl
  LEAF_Request_Portal/templates/menu.tpl
  LEAF_Request_Portal/templates/menu_links.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/submitForm.tpl
  LEAF_Request_Portal/templates/submitForm_parallel_processing.tpl
  LEAF_Request_Portal/templates/view_homepage.tpl
Labels: rc-ready

#1689 Rc/2022 10 13/sprint 40 c1
  LEAF_Nexus/css/style.css
  LEAF_Nexus/templates/menu.tpl
  LEAF_Nexus/templates/view_homepage.tpl
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/admin/templates/main.tpl
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/initial_form.tpl
  LEAF_Request_Portal/templates/main.tpl
  LEAF_Request_Portal/templates/menu.tpl
  LEAF_Request_Portal/templates/menu_links.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/submitForm.tpl
  LEAF_Request_Portal/templates/submitForm_parallel_processing.tpl
  LEAF_Request_Portal/templates/view_homepage.tpl
Labels: on-prod, on-preprod

#1668 LEAF-3118 Simplified interface for (workflow requirement) access management
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/Workflow.php
Labels: With QA

#1679 LEAF-3138: cleanup update services
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/Position.php
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/admin/templates/admin_sync_services.tpl
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/scripts/sync_services.php
  LEAF_Request_Portal/scripts/updateServicesFromOrgChart.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  docker/mysql/leaf_users.sql
  scripts/timebracketcmdtest.php
Labels: enhancement, rc-ready

#1688 LEAF 3150 UI update for IFTHEN multiselect scenarios
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: rc-ready

#1692 LEAF 3180 fix site distribution menu link
  LEAF_Request_Portal/admin/templates/menu.tpl
Labels: rc-ready

#1687 LEAF-3166/2450/3159 Added notes to View History and Report Builder
  LEAF_Nexus/templates/view_group.tpl
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/View.php
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/api/RESTfulResponse.php
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/api/controllers/NotesController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/Note.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: enhancement, rc-ready

#1694 LEAF-3166 Don't allow a blank note
  LEAF_Request_Portal/templates/print_form.tpl
Labels: bug

#1695 LEAF-3189 allow enter in comment box
  LEAF_Request_Portal/sources/Note.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: bug

#1696 LEAF-3191 hotfix sync services
  LEAF_Request_Portal/sources/System.php
Labels: bug, rc-ready

#1672 LEAF-3170 Add customization hooks in orgchart_* input widgets
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/js/nationalEmployeeSelector.js
  LEAF_Nexus/js/positionSelector.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready, draft

#1697 LEAF-3192 Don't allow notes to be added after completion
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement, rc-ready
