Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-07, with the labels that each got.

#1592 LEAF-2952: Hotfix for Report Builder Export
  LEAF_Request_Portal/js/formGrid.js
Labels: bug, hotfix, rc-ready

#1596 Prevent race condition
  LEAF_Request_Portal/admin/templates/mod_system.tpl
Labels: rc-ready

#1598 LEAF-2907 Time filters were not working as expected when other filters were cha
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: bug, With QA

#1591 Stop Edge prompting for language translation
  LEAF_Request_Portal/admin/templates/main.tpl
Labels: enhancement, rc-ready

#1581 LEAF 2896 move multiselect format queries to default case
  LEAF_Request_Portal/js/formSearch.js
Labels: bug, rc-ready

#1553 LEAF-2752: If/Then Forms (Dropdown)
  LEAF_Request_Portal/admin/templates/mod_conditions_editor.tpl
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/api/controllers/FormEditorController.php
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/sources/FormEditor.php
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022041800-2022050300.sql
Labels: feature, database, on-preprod

#1602 LEAF 2971 Report Builder exports: implement format check
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/formGrid.js
Labels: rc-ready

#1601 LEAF 2963 gitignore update
  .gitignore
Labels: With QA

#1606 LEAF-2921: Nexus primary admin Implementation
  LEAF_Nexus/admin/index.php
  LEAF_Nexus/admin/templates/menu.tpl
  LEAF_Nexus/admin/templates/mod_system.tpl
  LEAF_Nexus/admin/templates/setup_medical_center.tpl
  LEAF_Nexus/api/controllers/SystemController.php
  LEAF_Nexus/css/mod_system.css
  LEAF_Nexus/css/style.css
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/NationalEmployee.php
  LEAF_Nexus/sources/System.php
  LEAF_Nexus/templates/menu.tpl
  LEAF_Request_Portal/css/style.css
Labels: feature, rc-ready

#1609 Rc/2022 07 22/sprint 35 c1 take2
  CODEOWNERS
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/NationalEmployee.php
  LEAF_Request_Portal/admin/templates/main.tpl
  LEAF_Request_Portal/admin/templates/mod_conditions_editor.tpl
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/mod_system.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/api/controllers/FormEditorController.php
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/sources/FormEditor.php
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022041800-2022050300.sql
Labels: release, on-prod, on-preprod

#1565 Added search capability to timeline
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: enhancement

#1617 LEAF-3003: Hotfix Search Revert
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/NationalEmployee.php
Labels: bug, hotfix
