Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-05, with the labels that each got.

#1543 LEAF-2748: Add Logging to Email Templates
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/admin/templates/site_elements/generic_dialog.tpl
  LEAF_Request_Portal/api/controllers/EmailTemplateController.php
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/EmailTemplate.php
  LEAF_Request_Portal/sources/System.php
  libs/logger/formatters/emailTemplateFormatter.php
  libs/logger/formatters/loggableTypes.php
  libs/logger/logFormatter.php
Labels: feature

#1560 Rc/2022 05 10/sprint 29 c2
  LEAF_Nexus/sources/Data.php
  LEAF_Request_Portal/form.php
Labels: release, on-prod, on-preprod

#1563 LEAF-2855: Check if Directory Exists for Telemetry
  LEAF_Request_Portal/sources/Telemetry.php
Labels: bug, rc-ready

#1562 LEAF-2287: Workflow Group List
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: bug, rc-ready

#1561 LEAF 2768 preprod banner
  LEAF_Nexus/admin/templates/main.tpl
  LEAF_Nexus/templates/main.tpl
  LEAF_Request_Portal/admin/templates/main.tpl
  LEAF_Request_Portal/templates/main.tpl
Labels: enhancement, rc-ready

#1558 LEAF 2821 mod_form format change detection
  LEAF_Request_Portal/admin/templates/mod_form.tpl
Labels: bug, rc-ready
