Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-01, with the labels that each got.

#1520 Resolve DOM ID collision issue
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: hotfix, rc-ready

#1519 add upload file types requested by users
  libs/php-commons/CommonConfig.php
Labels: rc-ready

#1518 Reduce queries
  LEAF_Request_Portal/form.php
Labels: rc-ready

#1517 LEAF 2575 disable local users if not found on refresh
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Nexus/templates/view_employee.tpl
Labels: rc-ready

#1516 LEAF 2599 tabbing and enter for employee selection
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/js/nationalEmployeeSelector.js
  LEAF_Nexus/js/positionSelector.js
Labels: enhancement, feature, rc-ready

#1515 Simplify query debugging process
  LEAF_Request_Portal/form.php
Labels: rc-ready

#1512 Rewrite method to compute user upload directory size using only PHP.
  LEAF_Request_Portal/sources/Telemetry.php
Labels: rc-ready

#1511 LEAF-2557 newRow null fix
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, rc-ready

#1510 Bugfix/LEAF-2530: dropdown selection for orgchart formats
  LEAF_Nexus/css/employeeSelector.css
  LEAF_Nexus/css/groupSelector.css
  LEAF_Nexus/css/positionSelector.css
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/js/nationalEmployeeSelector.js
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/submitForm_parallel_processing.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, rc-ready

#1525 LEAF-2698 update logic to handle usernames with spaces
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/NationalEmployee.php
Labels: bug, rc-ready

#1523 LEAF-2626 edge case inbox error fix
  LEAF_Request_Portal/Inbox.php
Labels: bug, rc-ready

#1521 Feature/leaf 2627/advanced option display
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/form.php
Labels: enhancement, rc-ready

#1524 LEAF-2090: search/add employee enhancement
  LEAF_Nexus/js/dialogController.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/js/dialogController.js
  libs/jsapi/nexus/LEAFNexusAPI.js
Labels: rc-ready
