Repository department-of-veterans-affairs/LEAF, pull requests merged in 2022-12, with the labels that each got.

#1766 LEAF-3119: Fix database configuration
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022050300-2022110300.sql
Labels: hotfix

#1768 LEAF-3119 - disable button
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: hotfix

#1770 LEAF-3330 - Filenames with & would not delete
  LEAF_Request_Portal/form.php
Labels: bug, rc-ready

#1778 LEAF-3255: Fix setEventFolder Parameter Datatype
  LEAF_Request_Portal/FormWorkflow.php
Labels: bug, php, draft

#1779 LEAF-3231 Update orgchart_* widget customization
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#1772 Bug / LEAF-3334 / Dialog Box being displayed at bottom of page
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
Labels: bug, rc-ready, javascript

#1782 LEAF-3322 Fortify Scan Cross-Site scripting
  LEAF_Nexus/ajaxEmployee.php
  LEAF_Nexus/index.php
Labels: bug, With QA

#1784 LEAF-3308 Email Reminder timing text
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Workflow.php
Labels: feature, rc-ready

#1789 LEAF-3308 - Missing icon on step when email notification is enabled.
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: bug, hotfix

#1785 LEAF 3216 IFTHEN radio format
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement

#1788 LEAF 3350 form entry scroll behavior
  LEAF_Request_Portal/templates/form.tpl
Labels: enhancement

#1792 Rc/2022 12 21/sprint 44 c1
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/print_form.tpl
Labels: release, on-preprod
