Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-08, with the labels that each got.

#2063 Leaf 3841 - First round duplicate workflows
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/Workflow.php
Labels: enhancement, feature, rc-ready

#2058 Leaf 3891 - Remove unused empUID argument
  LEAF_Nexus/api/controllers/EmployeeController.php
  LEAF_Nexus/templates/view_employee.tpl
Labels: rc-ready

#2053 LEAF-3833 UX_Editor_Part_2
  LEAF_Request_Portal/admin/css/mod_templates.css
  LEAF_Request_Portal/admin/css/mod_templates_email.css
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/templates_history/leaf_programmer/1685037501_custom_dev_import.tpl
  LEAF_Request_Portal/templates_history/template_editor/1685036655_view_homepage.tpl
Labels: rc-ready

#2073 Leaf 3908 - minor php errors
  LEAF_Request_Portal/dynicons/index.php
  LEAF_Request_Portal/sources/Config.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/Group.php
  libs/loaders/Leaf_autoloader.php
Labels: rc-ready

#2046 Leaf 3867 - remove duplicate declaration
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/js/formSearchMultisite.js
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
Labels: With QA

#2072 Rc/2023 08 02/sprint 57 c2
  LEAF_Nexus/api/controllers/EmployeeController.php
  LEAF_Nexus/templates/view_employee.tpl
  LEAF_Request_Portal/admin/css/mod_templates.css
  LEAF_Request_Portal/admin/css/mod_templates_email.css
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/dynicons/index.php
  LEAF_Request_Portal/js/formSearchMultisite.js
  LEAF_Request_Portal/sources/Config.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates_history/leaf_programmer/1685037501_custom_dev_import.tpl
  LEAF_Request_Portal/templates_history/template_editor/1685036655_view_homepage.tpl
  libs/loaders/Leaf_autoloader.php
Labels: on-prod, on-preprod

#2075 Temporarily disable deep search
  LEAF_Nexus/sources/Employee.php
Labels: rc-ready

#2074 Add missing parentID
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2068 Leaf 3880 -disabled actions deceive
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/api/controllers/WorkflowRouteController.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/WorkflowRoute.php
Labels: bug, rc-ready

#2066 Leaf 3871 - sync services local backups
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/sources/System.php
Labels: bug, rc-ready

#2084 Boiler plate change
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
Labels: bug

#2083 Leaf 3932 - more error logs
  LEAF_Nexus/scripts/updateDatabase.php
  LEAF_Request_Portal/api/controllers/TemplateFileHistoryController.php
  LEAF_Request_Portal/dynicons/index.php
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/scripts/updateDatabase.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/System.php
Labels: bug, enhancement, rc-ready

#2067 LEAF 3899 fix field name
  LEAF_Nexus/sources/Employee.php
Labels: rc-ready

#2085 LEAF-3937: Attempt to clear cookies and fix sessions
  LEAF_Nexus/sources/Login.php
  LEAF_Request_Portal/sources/Login.php
Labels: rc-ready

#2088 Leaf 3902 - Update groups, service and user
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/Tag.php
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/api/controllers/ServiceController.php
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/scripts/sync_services.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023082400.sql
  libs/logger/DataActionLogger.php
  libs/logger/formatters/ServiceChiefFormatter.php
Labels: bug, enhancement, feature, rc-ready

#2095 LEAF-3951 - Grid in email not formatting
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, rc-ready

#2094 LEAF 3947 fix incorrect backups notification
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2105 Hotfix service chiefs not deleting
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
Labels: bug, With QA

#2098 LEAF-3910 Remove import form
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
Labels: rc-ready

#2097 Leaf 2784 - comments on cancel
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement, feature, rc-ready

#2091 LEAF-3776: AD Distro Group Integration Part 1
  LEAF_Nexus/api/controllers/ActiveDirectoryController.php
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/sources/ActiveDirectory.php
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/site_elements/import_dialog.tpl
Labels: rc-ready, php, javascript, draft

#2090 Leaf 3556 - update dependency privs
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/sources/Group.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023082400.sql
Labels: enhancement, rc-ready

#2089 LEAF-3949 Only load relevant data
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2092 LEAF-3950 LEAF-S and Admin user flow update
  LEAF_Nexus/api/RESTfulResponse.php
  LEAF_Request_Portal/admin/templates/mod_system.tpl
  LEAF_Request_Portal/api/RESTfulResponse.php
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/js/LeafSecureReviewDialog.js
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/reports/LEAF_start_leaf_secure_certification.tpl
Labels: rc-ready

#2112 LEAF-3976 - Email sending on behalf of the requester not person taking action
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, With QA

#2118 Leaf 3989 - no comment on cancel
  LEAF_Request_Portal/sources/Form.php
Labels: bug
