Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-12, with the labels that each got.

#2230 Leaf 4130 - update string found
  scripts/evolving.php
  scripts/time_to_evolve.php
Labels: enhancement

#2256 Leaf 4186 - Persist original parameters
  LEAF_Request_Portal/js/formQuery.js
Labels: rc-ready

#2253 LEAF-4107-Remove-Console-Logs-From-Editors
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
Labels: rc-ready

#2252 Leaf 4173 - Prevent invalid query
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2251 Leaf 4172 - Avoid ambiguous query when used in combination with a data query
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2250 Leaf 4171 - Improve customizability for Employee Selector
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/nationalEmployeeSelector.js
Labels: rc-ready

#2249 LEAF 4166 prevent checkmark if initial value is empty
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: rc-ready

#2244 LEAF-4155: Custom Fields not added to non-custom email templates
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, rc-ready, php, draft
