Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-03, with the labels that each got.

#1848 LEAF-3346 - automated emails iteration after the first email
  LEAF_Request_Portal/Login.php
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Workflow.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023012400-2023012600.sql
  scripts/scheduled-task-commands/automatedEmailReminder.php
Labels: feature, rc-ready

#1847 LEAF-3486 - Correct the site root and error output
  LEAF_Request_Portal/Email.php
  LEAF_Request_Portal/scripts/automated_email.php
Labels: bug, rc-ready

#1867 LEAF-3562 - autoloader automated email
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Login.php
Labels: bug

#1868 Create LEAF_coach_key.php
  LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
Labels: bug, enhancement

#1870 Bug/autoloader/fixes
  LEAF_Nexus/admin/index.php
  LEAF_Nexus/dynicons/index.php
  LEAF_Nexus/qrcode/index.php
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
  LEAF_Request_Portal/dynicons/index.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/mailer/mailer.php
  LEAF_Request_Portal/qrcode/index.php
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/scripts/events/CustomEvent_LeafSecure_DeveloperConsole.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  docker/env_files/globals_local.env
  docker/mysql/db/boilerplate/orgchart_boilerplate_empty.sql
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
  docs/InstallationConfiguration.md
  libs/loaders/Leaf_autoloader.php
  libs/logger/DataActionLogger.php
  libs/logger/LogFormatter.php
  libs/logger/LogItem.php
  libs/logger/formatters/DataActions.php
  libs/logger/formatters/EmailTemplateFormatter.php
  libs/logger/formatters/FormFormatter.php
  libs/logger/formatters/FormatOptions.php
  libs/logger/formatters/GroupFormatter.php
  libs/logger/formatters/LoggableTypes.php
  libs/logger/formatters/PortalGroupFormatter.php
  libs/logger/formatters/PrimaryAdminFormatter.php
  libs/logger/formatters/ServiceChiefFormatter.php
  libs/logger/formatters/WorkflowFormatter.php
  libs/php-commons/Dynicon.php
  libs/smarty/plugins/modifier.sanitize.php
Labels: bug

#1872 LEAF-3536: Fix Request URI path
  LEAF_Request_Portal/scripts/automated_email.php
Labels: bug, hotfix

#1871 LEAF-3564: Remove "LEAF Team" text from email
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
  LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_body.tpl
Labels: enhancement

#1877 LEAF-3573: Update National Standard Deploy
  LEAF_Request_Portal/utils/LEAF_exportStandardConfig.php
  LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
Labels: bug, hotfix

#1875 Docker: Update DB for Autoloader
  docker/docker-compose.yml
  docs/InstallationConfiguration.md
Labels: enhancement, database

#1887 LEAF-3751 - dynicons backward compatibility
  docker/nginx/leaf_nginx.conf.template
Labels: rc-ready

#1883 LEAF-3570: Custom Email and Error Log Cleanup
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: bug, rc-ready

#1882 LEAF 3515 update order for default value display
  LEAF_Request_Portal/admin/templates/mod_form.tpl
Labels: rc-ready

#1880 LEAF 3559 and 3560 - ifthen format updates
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: enhancement, rc-ready

#1876 LEAF-3572 - When the addl days not set the email will not get the the information
  LEAF_Request_Portal/scripts/automated_email.php
Labels: bug, rc-ready

#1874 LEAF-3569: Gallery Update Verbiage
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  libs/dynicons/gallery.php
Labels: bug, enhancement, rc-ready

#1873 LEAF-3566: Sync Services Backup Cleanup
  LEAF_Request_Portal/sources/System.php
Labels: bug, enhancement, rc-ready

#1861 LEAF-2390: Improve Group Form History
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/view_history.tpl
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  libs/logger/DataActionLogger.php
  libs/logger/LogFormatter.php
  libs/logger/formatters/EmailTemplateFormatter.php
  libs/logger/formatters/FormFormatter.php
  libs/logger/formatters/FormatOptions.php
  libs/logger/formatters/GroupFormatter.php
  libs/logger/formatters/PortalGroupFormatter.php
  libs/logger/formatters/PrimaryAdminFormatter.php
  libs/logger/formatters/ServiceChiefFormatter.php
  libs/logger/formatters/TemplateEditorFormatter.php
  libs/logger/formatters/TemplateReportsFormatter.php
  libs/logger/formatters/WorkflowFormatter.php
Labels: enhancement, rc-ready, php

#1860 LEAF-3547 Fix Report Builder: Date Cancelled
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#1857 LEAF-3555: Avoid using grid.loadData in the example
  LEAF_Request_Portal/templates/reports/example.tpl
Labels: enhancement, rc-ready

#1855 Leaf 3529 - update record id in notes
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023012600-2023022300.sql
Labels: bug, database, rc-ready

#1862 LEAF-3552 - Sanitize Log Error - Fortify
  LEAF_Nexus/utils/countFTEceiling.php
Labels: enhancement, rc-ready

#1890 LEAF-3615 - refresh orgchart employees script
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: hotfix

#1889 Rc/2023 03 21/sprint 49 c1
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Nexus/utils/countFTEceiling.php
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/admin/templates/view_history.tpl
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/scripts/splitConfig.php
  LEAF_Request_Portal/scripts/updateDatabase.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/reports/example.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023012600-2023022300.sql
  docker/nginx/leaf_nginx.conf.template
  libs/dev_only_scripts/customEvent.php
  libs/dev_only_scripts/customTemplate.php
  libs/dev_only_scripts/dump_form_data_to_sql_server.php
  libs/dev_only_scripts/moveConfigs.php
  libs/dynicons/gallery.php
  libs/logger/DataActionLogger.php
  libs/logger/LogFormatter.php
  libs/logger/formatters/EmailTemplateFormatter.php
  libs/logger/formatters/FormFormatter.php
  libs/logger/formatters/FormatOptions.php
  libs/logger/formatters/GroupFormatter.php
  libs/logger/formatters/PortalGroupFormatter.php
  libs/logger/formatters/PrimaryAdminFormatter.php
  libs/logger/formatters/ServiceChiefFormatter.php
  libs/logger/formatters/TemplateEditorFormatter.php
  libs/logger/formatters/TemplateReportsFormatter.php
  libs/logger/formatters/WorkflowFormatter.php
Labels: release

#1881 LEAF-3505: Rename Workflows
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/Workflow.php
  libs/logger/DataActionLogger.php
  libs/logger/formatters/LoggableTypes.php
  libs/logger/formatters/WorkflowFormatter.php
Labels: feature, rc-ready, php, javascript, draft

#1884 LEAF 3411 add decode for excel 'from web' import
  LEAF_Request_Portal/api/RESTfulResponse.php
  LEAF_Request_Portal/sources/Shortener.php
Labels: rc-ready

#1878 LEAF-3568 - Copy request_service does not show on non admin
  LEAF_Request_Portal/api/controllers/ServiceController.php
  LEAF_Request_Portal/api/index.php
Labels: bug, rc-ready

#1896 Leaf 3176 - refactor RESTfulResponse
  LEAF_Request_Portal/api/RESTfulResponse.php
  LEAF_Request_Portal/api/controllers/ClassicPhonebookController.php
  LEAF_Request_Portal/api/controllers/ConverterController.php
  LEAF_Request_Portal/api/controllers/EmailTemplateController.php
  LEAF_Request_Portal/api/controllers/FTEdataController.php
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/api/controllers/FormEditorController.php
  LEAF_Request_Portal/api/controllers/FormStackController.php
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/api/controllers/IconPickerController.php
  LEAF_Request_Portal/api/controllers/ImportController.php
  LEAF_Request_Portal/api/controllers/InboxController.php
  LEAF_Request_Portal/api/controllers/NotesController.php
  LEAF_Request_Portal/api/controllers/OpenController.php
  LEAF_Request_Portal/api/controllers/ServiceController.php
  LEAF_Request_Portal/api/controllers/SignatureController.php
  LEAF_Request_Portal/api/controllers/SimpleDataController.php
  LEAF_Request_Portal/api/controllers/SiteController.php
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/api/controllers/TelemetryController.php
  LEAF_Request_Portal/api/controllers/TemplateEditorController.php
  LEAF_Request_Portal/api/controllers/TemplateReportsController.php
  LEAF_Request_Portal/api/controllers/UserActivity.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/auth_domain/api/index.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/scripts/events/CustomEvent_LeafSecure_DeveloperConsole.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/VAMC_Directory.php
Labels: enhancement, rc-ready
