Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-07, with the labels that each got.

#1996 LEAF-3781: Add error handling
  libs/js/LEAF/formSearch.js
  libs/js/LEAF/intervalQueue.js
Labels: rc-ready

#2005 LEAF 3805 - Allow custom workflow preconditions to modify the comment
  LEAF_Request_Portal/js/workflow.js
Labels: rc-ready

#2014 Leaf 3818 - connect button to new api
  LEAF_Nexus/admin/index.php
  LEAF_Nexus/admin/templates/admin_refresh_directory.tpl
  LEAF_Nexus/sources/Employee.php
  libs/php-commons/Db.php
Labels: enhancement

#2016 LEAF 3803 fix group search non-unique results
  LEAF_Nexus/sources/Group.php
Labels: rc-ready

#2032 LEAF-3840: Workflow Error Pops up in Edge Case
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, php, draft

#2029 Rc/2023 07 05/sprint 55 c1
  LEAF_Nexus/admin/index.php
  LEAF_Nexus/admin/templates/admin_refresh_directory.tpl
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/Group.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/FormWorkflow.php
  libs/js/LEAF/formSearch.js
  libs/js/LEAF/intervalQueue.js
  libs/php-commons/Db.php
Labels: release, on-prod, on-preprod

#2024 LEAF-3837: Add "get help" button and remove unnecessary alt tags
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
Labels: enhancement, rc-ready

#2021 Leaf 3806 - refactor set primary admin
  LEAF_Request_Portal/sources/Group.php
Labels: enhancement, rc-ready

#2012 LEAF-3827: Check array length before accessing
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2043 Leaf 3855 - widen fields
  LEAF_Request_Portal/templates/initial_form.tpl
Labels: rc-ready

#2042 LEAF 3830 - backup submit errors and behavior
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: rc-ready

#2044 LEAF 3808 - ifthen tooltip updater for old interface
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: rc-ready

#2035 LEAF-3843: Days Since Last Action Deleted Records
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: bug, rc-ready, javascript, draft

#2028 LEAF-3756: Combined Inbox Dynamic Column Loading
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Labels: enhancement, rc-ready, javascript, draft

#2019 LEAF-3561 - Upload employee data to orgchart
  LEAF_Nexus/admin/templates/orgChart_import.tpl
  libs/jsapi/nexus/LEAFNexusAPI.js
Labels: bug, rc-ready

#2052 Quick fix to rc
  LEAF_Request_Portal/sources/System.php
Labels: bug, hotfix

#2055 LEAF-3884 api point not backwards compatible
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  libs/js/LEAF/formSearch.js
Labels: rc-ready

#2057 Leaf 3888 - Change Current Step: implementation using existing APIs
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: rc-ready

#2056 Leaf 3887 - fix incorrect indicator
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2054 LEAF-3881 - Incorrect error messge in Report Builder
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2047 LEAF 3863 form and indicator change detection
  LEAF_Request_Portal/admin/templates/mod_form.tpl
Labels: rc-ready

#2045 Leaf 3866 - auto expand comment field
  LEAF_Request_Portal/js/workflow.js
Labels: rc-ready

#2033 LEAF-3842: Initialize Return Variable
  LEAF_Request_Portal/sources/Email.php
Labels: rc-ready

#2051 LEAF 3875 - ifthen data optimizations
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/dialog_content/ConditionsEditorDialog.js
  libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  libs/js/vue-dest/site_designer/LEAF_Designer.js
Labels: rc-ready

#2037 Leaf - 3364 user groups users with backups not right
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
  LEAF_Request_Portal/scripts/firstRun.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023052500-2023072000.sql
Labels: bug, database, rc-ready
