Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-05, with the labels that each got.

#1957 Hotfix config reconfig
  LEAF_Nexus/api/controllers/NationalEmployeeController.php
  LEAF_Nexus/scripts/VAMC_directory_maintenance2_AD.php
  LEAF_Nexus/scripts/syncSVNrevision.php
  LEAF_Nexus/sources/Config.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/scripts/VAMC_directory_maintenance2_AD.php
  LEAF_Request_Portal/sources/Config.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/templates/sitemap.tpl
  libs/loaders/Leaf_autoloader.php
Labels: hotfix

#1956 Issue/leaf 3683/fe banner fix feature updates
  docker/vue-app/src/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/LEAF_IfThen.scss
  docker/vue-app/src/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/components/dialog_content/ImportFormDialog.js
  docker/vue-app/src/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/components/form_editor_view/FormBrowser.js
  docker/vue-app/src/views/FormEditorView.js
  libs/js/vue-dest/LEAF_FormEditor_main_build.js
Labels: rc-ready

#1961 LEAF-3714 - File History Limit
  LEAF_Request_Portal/sources/TemplateFileHistory.php
  LEAF_Request_Portal/sources/TemplateReports.php
Labels: rc-ready

#1965 LEAF-3725: Hotfix - Update FormWorkflow.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, hotfix, php, With QA

#1969 Hotfix: LEAF-3276: Missing MySQL 8 update groups
  LEAF_Request_Portal/sources/FormEditor.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/System.php
Labels: hotfix, rc-ready, php

#1963 LEAF-3711: Primary Admin History Fix
  LEAF_Request_Portal/sources/System.php
Labels: bug, rc-ready, php, draft

#1962 LEAF 3635 grid format - load options from file celltype
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/gridInput.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#1970 Hotfix: Boilerplate Email Fix
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
Labels: With QA

#1971 Leaf 2789 Tracking emails sent
  LEAF_Request_Portal/js/pages/mass_action.js
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/EmailTracker.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/View.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/view_status.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023040700-2023052500.sql
Labels: enhancement, database, rc-ready

#1960 Leaf 3708 Automated Email code missing
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/scripts/automated_email.php
Labels: bug, rc-ready

#1972 Leaf 3272 - added successful post notification
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/site_elements/generic_OkDialog.tpl
Labels: enhancement, rc-ready
