Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-09, with the labels that each got.

#2108 Leaf 3973 hotfix sync services
  LEAF_Nexus/sources/Group.php
Labels: bug, hotfix, rc-ready, on-prod, on-preprod

#2111 LEAF-3979 - Compatibility for upcoming large query handler
  LEAF_Request_Portal/js/formQuery.js
Labels: rc-ready

#2113 LEAF-3978 - Optimize autoloader DB connections
  LEAF_Request_Portal/scripts/events/CustomEvent_LeafSecure_DeveloperConsole.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/VAMC_Directory.php
Labels: rc-ready

#2093 LEAF-3945 - refreshOrgchartEmployees not run on all orgcharts
  scripts/scheduled-task-commands/refreshOrgchartEmployees.php
Labels: bug, rc-ready

#2115 LEAF-3977 - org chart employee field in import data error
  libs/jsapi/nexus/LEAFNexusAPI.js
Labels: bug, rc-ready

#2126 LEAF-4004 - Inbox v2
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
  LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
  LEAF_Request_Portal/templates/view_homepage.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  libs/js/LEAF/intervalQueue.js
Labels: rc-ready

#2122 LEAF-3996 - Update error message
  libs/php-commons/Db.php
Labels: rc-ready

#2117 LEAF-3998 - Improve ergonomics of getData() when using many indicators
  LEAF_Request_Portal/js/formQuery.js
Labels: rc-ready

#2136 Leaf 4014 - foreign key correction
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
Labels: rc-ready

#2127 LEAF-4007 - Prepare for fulltext search feature
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023082401-2023091100.sql
Labels: rc-ready
