Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-04, with the labels that each got.

#1932 LEAF 3501 duplicate text issue and 'no format' text formatting
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#1901 LEAF 2839 ifthen support for option loading and crosswalk
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/templates/print_form.tpl
Labels: rc-ready

#1888 LEAF-3508 - fortify report remove momentjs
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  libs/js/moment/moment-timezone-with-data.min.js
  libs/js/moment/moment.min.js
Labels: bug, rc-ready

#1927 LEAF-3587: Supervisor error catch
  LEAF_Nexus/sources/Position.php
  LEAF_Nexus/templates/view_position.tpl
Labels: bug, rc-ready

#1926 LEAF-3588: Fix count check on file/image url
  LEAF_Request_Portal/file.php
  LEAF_Request_Portal/image.php
Labels: bug, rc-ready

#1897 LEAF-3606 - automated email days ticket has been open
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
Labels: feature, rc-ready

#1898 LEAF-3607: Removed IE Workaround
  LEAF_Request_Portal/js/formGrid.js
Labels: bug, rc-ready, javascript

#1894 LEAF 3618 - Update formSearch.js validation - Fortify
  libs/js/LEAF/formSearch.js
Labels: rc-ready

#1895 LEAF 3617 - Update jsonExport_PDL.php - Fortify
  LEAF_Nexus/utils/jsonExport_PDL.php
Labels: rc-ready

#1938 Rc/2023 04 11/sprint 50 c1
  LEAF_Nexus/sources/Position.php
  LEAF_Nexus/templates/view_position.tpl
  LEAF_Nexus/utils/jsonExport_PDL.php
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/file.php
  LEAF_Request_Portal/image.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  libs/js/LEAF/formSearch.js
  libs/js/moment/moment-timezone-with-data.min.js
  libs/js/moment/moment.min.js
Labels: on-prod, on-preprod

#1931 LEAF-3596 file upload copy error
  LEAF_Request_Portal/templates/print_form.tpl
Labels: bug, rc-ready

#1929 LEAF 3636: address uncovered bugs and COP feedback
  LEAF_Request_Portal/sources/FormStack.php
  docker/vue-app/src/components/GridCell.js
  docker/vue-app/src/components/ModFormMenu.js
  docker/vue-app/src/components/dialog_content/ConfirmDeleteDialog.js
  docker/vue-app/src/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/views/RestoreFieldsView.js
  libs/js/vue-dest/LEAF_FormEditor_main_build.js
Labels: rc-ready

#1928 Leaf 3611 adding signature to db
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/Signature.php
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: enhancement, rc-ready

#1936 LEAF-3435: Combined Inbox Implementation
  LEAF_Request_Portal/api/controllers/SiteController.php
  LEAF_Request_Portal/sources/Site.php
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
  LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
  LEAF_Request_Portal/templates/sitemap.tpl
Labels: feature, rc-ready, php, javascript, draft

#1948 Leaf 3677 hot fix nexus summary
  LEAF_Nexus/utils/jsonExport_PDL.php
Labels: bug, rc-ready

#1945 LEAF 3660 option load edgecase fix
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: rc-ready

#1939 Leaf 3584 - refactor config
  .gitignore
  LEAF_Nexus/file.php
  LEAF_Nexus/image.php
  LEAF_Nexus/index.php
  LEAF_Nexus/scripts/VAMC_directory_maintenance2_AD.php
  LEAF_Nexus/scripts/convertFileNames.php
  LEAF_Nexus/scripts/syncSVNrevision.php
  LEAF_Nexus/sources/Config.php
  LEAF_Nexus/sources/Data.php
  LEAF_Nexus/sources/Tag.php
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/view_history.tpl
  LEAF_Request_Portal/ajaxIframe.php
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/file.php
  LEAF_Request_Portal/image.php
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/scripts/firstRun.php
  LEAF_Request_Portal/sources/Config.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/VAMC_Directory.php
  docs/InstallationConfiguration.md
  libs/loaders/Leaf_autoloader.php
  libs/php-commons/Db.php
  libs/php-commons/Setting.php
Labels: enhancement, rc-ready

#1937 LEAF-3507 Merge.js Race Condition Issue
  libs/js/codemirror/addon/merge/merge.js
Labels: rc-ready

#1935 LEAF-2034 Add File Tracking to Editors
  .gitignore
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/api/controllers/EmailTemplateController.php
  LEAF_Request_Portal/api/controllers/TemplateFileHistoryController.php
  LEAF_Request_Portal/api/controllers/TemplateReportsController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/EmailTemplate.php
  LEAF_Request_Portal/sources/TemplateEditor.php
  LEAF_Request_Portal/sources/TemplateFileHistory.php
  LEAF_Request_Portal/sources/TemplateReports.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023030900-2023040700.sql
  libs/logger/DataActionLogger.php
  libs/logger/formatters/DataActions.php
  libs/logger/formatters/EmailTemplateFormatter.php
  libs/logger/formatters/LoggableTypes.php
  libs/logger/formatters/TemplateEditorFormatter.php
  libs/logger/formatters/TemplateReportsFormatter.php
Labels: feature, rc-ready, php, javascript
