Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-02, with the labels that each got.

#1825 Leaf 3463 - Restore supplemental orgchart info
  LEAF_Request_Portal/FormWorkflow.php
Labels: rc-ready

#1822 LEAF-2381 - Email No recipient
  LEAF_Request_Portal/Email.php
Labels: bug, rc-ready

#1818 LEAF 2459 add warning to subordinate sites
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/admin/templates/form_editor_vue.tpl
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: rc-ready

#1816 LEAF-3424 - Email Reminders not working on National sites
  LEAF_Request_Portal/scripts/automated_email.php
Labels: bug, rc-ready

#1831 LEAF 2381 - email address can come in as null
  LEAF_Request_Portal/Email.php
Labels: bug

#1828 Leaf 3468 - Handle large queries within customizations gracefully
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/templates/reports/example.tpl
Labels: rc-ready

#1827 LEAF-2666: orgchart format indicators should have a proper selector for default values
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: enhancement, rc-ready, javascript, draft

#1835 Leaf 3478 - Simplify debugging
  LEAF_Request_Portal/sources/Shortener.php
Labels: rc-ready

#1833 Leaf 3480 - Improve compatibility for multi-site interactivity
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/scripts/workflowStepModules/LEAF_workflow_indicator.tpl
  LEAF_Request_Portal/scripts/workflowStepModules/TEMPLATE_workflowStepModule.tpl
Labels: rc-ready

#1834 Leaf 3481 - Enable "contains" condition for dropdown/radio searches
  LEAF_Request_Portal/js/formSearch.js
Labels: rc-ready

#1838 LEAF-3502 - Remove dead code
  LEAF_Request_Portal/api/controllers/FormStackController.php
  docker/swagger/portal-swagger.json
Labels: rc-ready

#1846 LEAF-3519 - Workaround race condition
  LEAF_Request_Portal/js/formSearch.js
Labels: rc-ready

#1837 LEAF-2875 Mark old accounts as disabled
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: rc-ready, php

#1839 LEAF-3434: Combined Inbox Part 1: Update sitemap editor
  LEAF_Request_Portal/api/controllers/IconPickerController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/IconPIcker.php
  LEAF_Request_Portal/templates/reports/LEAF_sitemaps_template.tpl
  LEAF_Request_Portal/templates/sitemap.tpl
Labels: enhancement, feature, rc-ready, php, javascript, draft

#1853 Revert "LEAF-3518 - Temporarily disable site distribution"
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
Labels: rc-ready, revert

#1849 LEAF 3398 file del endpoint update
  LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
  LEAF_Request_Portal/api/controllers/SystemController.php
Labels: rc-ready

#1840 LEAF 3327 New Account Updater
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/Group.php
  LEAF_Nexus/sources/Position.php
  LEAF_Request_Portal/VAMC_Directory.php
  LEAF_Request_Portal/admin/Group.php
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/reports/LEAF_request_initiator_new_account.tpl
Labels: rc-ready

#1844 LEAF-3517 - Avoid redundant queries
  LEAF_Request_Portal/form.php
Labels: rc-ready

#1843 LEAF-3516 - Report builder sort persistence
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#1842 LEAF-3513 - Fix length check
  LEAF_Request_Portal/admin/templates/mod_system.tpl
Labels: rc-ready

#1850 LEAF- 3534 - Align with HTTP specification for etags
  LEAF_Nexus/api/RESTfulResponse.php
  LEAF_Request_Portal/api/RESTfulResponse.php
Labels: rc-ready
