Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-06, with the labels that each got.

#1987 Leaf 3760/remove db config
  LEAF_Request_Portal/sources/Config.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
Labels: enhancement, rc-ready

#1985 LEAF 3712 orgchart formats for ifthen
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
  docker/vue-app/src/LEAF_FormEditor.scss
  docker/vue-app/src/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/LEAF_IfThen.scss
  docker/vue-app/src/components/ModFormMenu.js
  docker/vue-app/src/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/components/form_editor_view/CategoryItem.js
  docker/vue-app/src/components/form_editor_view/EditPropertiesPanel.js
  docker/vue-app/src/components/form_editor_view/FormatPreview.js
  docker/vue-app/src/views/FormEditorView.js
  libs/js/vue-dest/LEAF_FormEditor_main_build.js
Labels: rc-ready

#1984 Leaf 3546 - API code consistency
  LEAF_Nexus/admin/templates/mod_templates_reports.tpl
  LEAF_Nexus/api/controllers/SystemController.php
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/api/controllers/AppletController.php
  LEAF_Request_Portal/api/controllers/TemplateController.php
  LEAF_Request_Portal/api/controllers/TemplateReportsController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/Applet.php
  LEAF_Request_Portal/sources/Template.php
  LEAF_Request_Portal/templates_history/leaf_programmer/1685037501_custom_dev_import.tpl
  LEAF_Request_Portal/templates_history/template_editor/1685036655_view_homepage.tpl
  libs/logger/DataActionLogger.php
  libs/logger/LogFormatter.php
  libs/logger/formatters/AppletFormatter.php
  libs/logger/formatters/TemplateFormatter.php
Labels: enhancement, rc-ready

#1982 LEAF-3628: LEAF print function prints all options available for each question
  LEAF_Request_Portal/js/formPrint.js
Labels: bug, rc-ready, javascript, draft

#1981 LEAF-3436: Combined Inbox Customization
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_combined_inbox.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.css
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
  LEAF_Request_Portal/sources/Site.php
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Labels: feature, rc-ready, php, javascript, draft

#1978 Leaf 3748 menu changed
  LEAF_Request_Portal/admin/templates/menu.tpl
Labels: enhancement, rc-ready

#1977 LEAF-3696 Email Template Update
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
Labels: bug, rc-ready, javascript

#1991 LEAF 3775 fix path to datepicker plugin
  LEAF_Request_Portal/js/formSearch.js
Labels: rc-ready

#2003 LEAF-3791: Combined Inbox not Viewable by Non-Admins
  LEAF_Request_Portal/api/index.php
Labels: bug, rc-ready, php, draft

#2002 LEAF-3790: Email Class not Working on New Portals
  libs/loaders/Leaf_autoloader.php
Labels: bug, rc-ready, php

#2001 Leaf 3783 - admin dropdown addition
  LEAF_Request_Portal/admin/templates/menu.tpl
Labels: enhancement, rc-ready

#1999 Leaf 3774 - refresh orgchart employee api
  LEAF_Nexus/api/controllers/EmployeeController.php
  LEAF_Nexus/api/index.php
  LEAF_Nexus/index.php
  LEAF_Nexus/scripts/batchRefreshEmployees.php
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/templates/print_subindicators.tpl
  LEAF_Nexus/templates/site_elements/generic_OkDialog.tpl
  LEAF_Nexus/templates/view_employee.tpl
Labels: enhancement, rc-ready

#1998 LEAF 3773 portal js cleanup 1 (formQuery)
  LEAF_Request_Portal/js/formQuery.js
  libs/js/LEAF/formQuery.js
Labels: rc-ready

#1997 LEAF 3772 action info and general mod_workflow cleanup
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: rc-ready

#1995 LEAF 3732 Add File Manager Form Info
  LEAF_Request_Portal/admin/css/style.css
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_file_manager.tpl
Labels: rc-ready

#1992 LEAF-3685: Uploading File via Combined Inbox
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
Labels: bug, rc-ready, javascript

#2006 Leaf 1830 - send back comment
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowRouteController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/sources/WorkflowRoute.php
  LEAF_Request_Portal/templates/reports/LEAF_inbox_combined.tpl
  LEAF_Request_Portal/templates/view_inbox.tpl
  libs/php-commons/Db.php
Labels: enhancement, rc-ready

#1988 LEAF_3709 - Template Editor UX
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
Labels: rc-ready

#2004 LEAF 3804 - allow custom hashes as recordID
  LEAF_Request_Portal/js/formGrid.js
Labels: rc-ready

#2023 Hotfix - LEAF-3832: Quick Search Dropdown Not Working With One Option
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
Labels: hotfix, javascript
