Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-11, with the labels that each got.

#2218 LEAF-4110: Sitemap Font Color for combined inbox
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: bug

#2214 LEAF 2122 dialog modal and button related issues
  LEAF_Nexus/js/dialogController.js
  LEAF_Nexus/templates/permission_iframe.tpl
  LEAF_Nexus/templates/print_subindicators.tpl
  LEAF_Nexus/templates/view_group.tpl
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/admin/templates/print_form_ajax.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/print_form_ajax.tpl
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_inbox.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2213 Leaf 3921 - refactor db update
  LEAF_Nexus/scripts/updateDatabase.php
  LEAF_Request_Portal/scripts/updateDatabase.php
  app/Leaf/DbUpdate.php
  app/Leaf/Setting.php
Labels: enhancement, rc-ready

#2222 LEAF-4123: Optimize "group designated" hotspot
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2220 LEAF-4122: Programmer UX
  LEAF_Request_Portal/admin/css/mod_templates.css
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
Labels: rc-ready

#2219 LEAF-4121: Fulltext search
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2217 LEAF-4120: Update filter
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2216 LEAF-4119: Prevent invalid query
  LEAF_Request_Portal/sources/Form.php
Labels: bug, rc-ready

#2242 LEAF-4157 - Resolve UX issue in formSearch.js
  LEAF_Request_Portal/js/formSearch.js
Labels: hotfix, rc-ready

#2239 LEAF 2747 Email Template Editor notification info
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/sources/Workflow.php
Labels: rc-ready

#2238 LEAF 3971 conditions editor new question display
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
Labels: rc-ready

#2235 LEAF 4139 update keypress listeners in orgchartForm
  LEAF_Nexus/js/orgchartForm.js
  LEAF_Nexus/templates/view_position.tpl
Labels: rc-ready

#2233 LEAF 4136 if/then additional child formats
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
Labels: rc-ready

#2229 LEAF 2531 (3188) file upload formats
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#2223 Leaf 4084 - custom emails added to subordinate
  LEAF_Request_Portal/utils/LEAF_importStandardConfig.php
  app/libs/loaders/Leaf_autoloader.php
Labels: enhancement, feature, With QA

#2224 LEAF 4111 gridInput file cleanup
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/js/gridInput.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready
