Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-01, with the labels that each got.

#1797 LEAF-3363: Session Expire Verbiage Change
  LEAF_Request_Portal/templates/view_session_expire.tpl
Labels: enhancement, rc-ready

#1795 LEAF 3356 docker container for Form Editor, 3309 related information
  .gitignore
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/form_editor_vue.tpl
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/api/controllers/FormStackController.php
  docker/docker-compose.yml
  docker/env_files/vue_ui_local.env
  docker/vue-app/.babelrc
  docker/vue-app/.dockerignore
  docker/vue-app/leaf_vue.dockerfile
  docker/vue-app/package.json
  docker/vue-app/src/LEAF_FormEditor.scss
  docker/vue-app/src/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/LEAF_FormEditor_main.js
  docker/vue-app/src/LEAF_IfThen.scss
  docker/vue-app/src/components/CategoryCard.js
  docker/vue-app/src/components/GridCell.js
  docker/vue-app/src/components/IndicatorPrivileges.js
  docker/vue-app/src/components/LeafFormDialog.js
  docker/vue-app/src/components/ModFormMenu.js
  docker/vue-app/src/components/RestoreFields.js
  docker/vue-app/src/components/dialog_content/AdvancedOptionsDialog.js
  docker/vue-app/src/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/components/dialog_content/ConfirmDeleteDialog.js
  docker/vue-app/src/components/dialog_content/EditCollaboratorsDialog.js
  docker/vue-app/src/components/dialog_content/FormHistoryDialog.js
  docker/vue-app/src/components/dialog_content/ImportFormDialog.js
  docker/vue-app/src/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/components/dialog_content/NewFormDialog.js
  docker/vue-app/src/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/components/form_view/EditPropertiesPanel.js
  docker/vue-app/src/components/form_view/FormEditingDisplay.js
  docker/vue-app/src/components/form_view/FormIndexListing.js
  docker/vue-app/src/components/form_view/FormViewController.js
  docker/vue-app/src/components/form_view/FormatPreview.js
  docker/vue-app/webpack.config.js
  docs/InstallationConfiguration.md
  libs/js/vue-dest/LEAF_FormEditor_main_build.js
Labels: review/comment only, With QA

#1794 LEAF-3362 - Fortify - Update momentjs to latest
  libs/js/moment/moment.min.js
Labels: bug, rc-ready

#1791 Feature/LEAF-2498/Add View History functionality
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/api/controllers/TemplateEditorController.php
  LEAF_Request_Portal/api/controllers/TemplateReportsController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/TemplateEditor.php
  LEAF_Request_Portal/sources/TemplateReports.php
  libs/logger/formatters/TemplateEditorFormatter.php
  libs/logger/formatters/TemplateReportsFormatter.php
  libs/logger/formatters/loggableTypes.php
  libs/logger/logFormatter.php
Labels: feature, rc-ready, php, javascript

#1798 LEAF-2551: Zero Account Validation
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: enhancement, javascript, draft

#1800 Add undefined check for zero account validator
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: hotfix, on-prod, on-preprod, javascript

#1799 Rc/2023 01 03/sprint 44 c4
  .gitignore
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/form_editor_vue.tpl
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/api/controllers/FormStackController.php
  LEAF_Request_Portal/api/controllers/SystemController.php
  LEAF_Request_Portal/api/controllers/TemplateEditorController.php
  LEAF_Request_Portal/api/controllers/TemplateReportsController.php
  LEAF_Request_Portal/api/index.php
  LEAF_Request_Portal/sources/System.php
  LEAF_Request_Portal/sources/TemplateEditor.php
  LEAF_Request_Portal/sources/TemplateReports.php
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/view_session_expire.tpl
  docker/docker-compose.yml
  docker/env_files/vue_ui_local.env
  docker/vue-app/.babelrc
  docker/vue-app/.dockerignore
  docker/vue-app/leaf_vue.dockerfile
  docker/vue-app/package.json
  docker/vue-app/src/LEAF_FormEditor.scss
  docker/vue-app/src/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/LEAF_FormEditor_main.js
  docker/vue-app/src/LEAF_IfThen.scss
  docker/vue-app/src/components/CategoryCard.js
  docker/vue-app/src/components/GridCell.js
  docker/vue-app/src/components/IndicatorPrivileges.js
  docker/vue-app/src/components/LeafFormDialog.js
  docker/vue-app/src/components/ModFormMenu.js
  docker/vue-app/src/components/RestoreFields.js
  docker/vue-app/src/components/dialog_content/AdvancedOptionsDialog.js
  docker/vue-app/src/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/components/dialog_content/ConfirmDeleteDialog.js
  docker/vue-app/src/components/dialog_content/EditCollaboratorsDialog.js
  docker/vue-app/src/components/dialog_content/FormHistoryDialog.js
  docker/vue-app/src/components/dialog_content/ImportFormDialog.js
  docker/vue-app/src/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/components/dialog_content/NewFormDialog.js
  docker/vue-app/src/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/components/form_view/EditPropertiesPanel.js
  docker/vue-app/src/components/form_view/FormEditingDisplay.js
  docker/vue-app/src/components/form_view/FormIndexListing.js
  docker/vue-app/src/components/form_view/FormViewController.js
  docker/vue-app/src/components/form_view/FormatPreview.js
  docker/vue-app/webpack.config.js
  docs/InstallationConfiguration.md
  libs/js/moment/moment.min.js
  libs/js/vue-dest/LEAF_FormEditor_main_build.js
  libs/logger/formatters/TemplateEditorFormatter.php
  libs/logger/formatters/TemplateReportsFormatter.php
  libs/logger/formatters/loggableTypes.php
  libs/logger/logFormatter.php
Labels: on-prod, on-preprod

#1806 LEAF 3392 ELT access issue
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/admin/index.php
Labels: hotfix, rc-ready, on-prod

#1809 Mitigate issue when "filled" status isn't updated
  LEAF_Request_Portal/FormWorkflow.php
Labels: rc-ready, on-prod, on-preprod

#1810 LEAF 3405 remaining ELT group access issues
  LEAF_Request_Portal/FormWorkflow.php
Labels: hotfix, on-prod, on-preprod, php, draft

#1808 Log error on server
  LEAF_Nexus/db_mysql.php
  LEAF_Request_Portal/db_mysql.php
Labels: rc-ready

#1807 LEAF 3336 escape quotes and apos in indicator names
  LEAF_Request_Portal/admin/templates/mod_form.tpl
Labels: rc-ready

#1805 LEAF 3217 checkboxes format for IFTHEN
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: rc-ready

#1812 Rc/2023 01 19/sprint 45 c2
  LEAF_Nexus/db_mysql.php
  LEAF_Request_Portal/admin/templates/mod_form.tpl
  LEAF_Request_Portal/admin/templates/print_subindicators.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/db_mysql.php
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/templates/print_form.tpl
Labels: on-prod, on-preprod

#1814 LEAF 3421 update specificity when looking for 'no' values
  LEAF_Request_Portal/form.php
Labels: hotfix, rc-ready

#1813 LEAF-3420 Add missing groupID
  LEAF_Request_Portal/form.php
Labels: hotfix, php, With QA

#1817 Leaf 3427 script to update db field
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2022110300-2023012400.sql
Labels: bug, database

#1823 Leaf 3437 - Replace arbitrary pop()
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#1821 Leaf 3431 - New query parameter: Actionable
  LEAF_Request_Portal/FormWorkflow.php
  LEAF_Request_Portal/form.php
  LEAF_Request_Portal/js/formSearch.js
Labels: rc-ready

#1820 Leaf 3430 Fix typo
  LEAF_Request_Portal/FormWorkflow.php
Labels: rc-ready
