Repository department-of-veterans-affairs/LEAF, pull requests merged in 2023-10, with the labels that each got.

#2154 LEAF 4038 timeline explorer infinite loop
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
Labels: rc-ready

#2152 Leaf 4037 - Resolve data type issues
  LEAF_Nexus/sources/Position.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2138 Leaf 4027 - Inbox v2 UX update
  LEAF_Request_Portal/templates/email/LEAF_notify_next_body.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready

#2139 Leaf 4031 - Optimize email hotspot
  LEAF_Request_Portal/sources/Email.php
Labels: rc-ready

#2160 Leaf 4043 - more info in dbupdate log
  LEAF_Request_Portal/scripts/updateDatabase.php
Labels: With QA

#2155 Leaf 4039 - Optimize "person designated" queries
  LEAF_Nexus/sources/Employee.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/VAMC_Directory.php
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023999999-2023092100.sql
Labels: With QA

#2162 Leaf 4048 - file found
  LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
  LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
Labels: bug, hotfix, on-prod

#2171 LEAF-3472 (Only DB): Large Queries DB Update
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023092100-2023100500.sql
Labels: database

#2172 DB Fix
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2020062600-2023092100.sql
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023091100-2023100500.sql
Labels: database

#2175 hotfix LEAF 4056 - Fix typo
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: on-prod

#2161 Rc/2023 10 3/sprint 62 c1
  LEAF_Nexus/sources/Employee.php
  LEAF_Nexus/sources/Position.php
  LEAF_Request_Portal/admin/templates/mod_access_matrix.tpl
  LEAF_Request_Portal/auth_domain/LEAF_coach_key.php
  LEAF_Request_Portal/scripts/updateDatabase.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/VAMC_Directory.php
  LEAF_Request_Portal/templates/email/LEAF_notify_next_body.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Timeline_Explorer.tpl
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_202062600-2023092100.sql
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023091100-2023100500.sql
Labels: database, on-prod, on-preprod

#2165 LEAF 4050 - Remove unused SQL JOIN
  LEAF_Request_Portal/sources/Email.php
Labels: rc-ready

#2151 LEAF 3913 - email reminders by scheduled date
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_body.tpl
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
Labels: rc-ready

#2150 LEAF - 4035 - New Account Updater Search Bug
  LEAF_Nexus/sources/Employee.php
Labels: rc-ready

#2185 LEAF-4077 - Add dependencyID check before overwriting approverName
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2178 LEAF 4062 - Optimize Form.php person designated access check (3 of 3)
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2177 LEAF 4061 - Optimize form/query and getCustomData's read access check (2 of 3)
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2167 Leaf 4010-2 - update references to copied files
  .gitignore
  LEAF_Nexus/qrcode/index.php
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/qrcode/index.php
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/templates/reports/coach_roster.tpl
  app/Leaf/Site.php
  app/libs/globals.php
  app/libs/globals_plus.php
  app/libs/loaders/Leaf_autoloader.php
  app/libs/smarty/plugins/modifier.sanitize.php
  app/libs/smarty/plugins/modifier.sanitizeRichtext.php
Labels: enhancement, rc-ready

#2190 LEAF 4065 update endpoint url
  LEAF_Request_Portal/js/LeafPreview.js
Labels: hotfix, rc-ready

#2176 LEAF 4060 - Optimize requestor followup (1 of 3)
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2193 LEAF 4088 - add isDisabled to indicator list x-dataFilter
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2159 Leaf 4042 - remove double unlink in mailer
  LEAF_Request_Portal/mailer/mailer.php
Labels: bug, rc-ready

#2201 LEAF-2090: User Access Groups - Add Employee Enhance
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
Labels: enhancement, rc-ready, javascript

#2210 LEAF-4015 - Resolve actionable query issue
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA

#2191 LEAF-4030: Multi Select Options on Email Templates not formatted correctly
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: bug, enhancement, rc-ready, php, draft

#2196 LEAF 4055 Combined Inbox Editor and Sitemap Search updates
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
Labels: rc-ready
