Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-07, with the labels that each got.

#2464 LEAF 4413 form editor, id back compat
  LEAF_Request_Portal/sources/Form.php
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
Labels: rc-ready, needs npm build

#2453 Leaf 4399 - form editor links and form import behavior
  LEAF_Request_Portal/admin/ajaxIndex.php
  LEAF_Request_Portal/admin/templates/view_form_library.tpl
  LEAF_Request_Portal/sources/FormStack.php
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/dialog_content/ImportFormDialog.js
Labels: rc-ready, needs npm build

#2437 Leaf 4397 - formGrid.js Accessibility improvements
  LEAF_Request_Portal/js/formGrid.js
Labels: rc-ready

#2474 LEAF-4426: VAPO Automated Emails
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024062000-2024071100.sql
  scripts/scheduled-task-commands/automatedEmailReminder.php
  scripts/scheduled-task-commands/automatedEmailReminderVAPO.php
Labels: With QA

#2466 LEAF 4410 - post action history user metadata
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA

#2456 LEAF-4428 Dev UX
  docker/docker-compose.yml
  docker/nginx/src/index.html
  docker/php/ssmtp/ssmtp.conf
  docs/InstallationConfiguration.md
Labels: With QA

#2465 LEAF 4420 - inbox group designated name display
  LEAF_Request_Portal/sources/FormWorkflow.php
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery.go
  x-test/API-tests/formQuery_test.go
Labels: With QA

#2473 Leaf 4376 - Processing AD Data
  app/Leaf/VAMCActiveDirectory.php
  scripts/scheduled-task-commands/updateNationalOrgchartEmployees.php
  scripts/updateNationalOrgchart.php
Labels: rc-ready

#2471 LEAF 4363 fix potential workflow copy issue
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/sources/Workflow.php
Labels: rc-ready

#2470 Leaf-4445 Promote x-filterData in the dev example
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2463 LEAF-4421 Simplify formGrid and example
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/nocode_templates/view_search.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/reports/example.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  LEAF_Request_Portal/templates/view_search.tpl
  app/libs/js/LEAF/formGrid.js
  libs/js/LEAF/formGrid.js
Labels: With QA
