Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-12, with the labels that each got.

#2602 LEAF 4435 dragdrop enhancements
  app/libs/css/leaf.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js.LICENSE.txt
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.css
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js.LICENSE.txt
  docker/vue-app/src/common/LEAF_Vue_Dialog__Common.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/components/form_editor_view/FormIndexListing.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  docker/vue-app/src/sass/leaf.scss
  docker/vue-app/src/site_designer/LEAF_Designer.scss
Labels: With QA

#2613 LEAF-4604 update form progress checking to account for conditional logic
  LEAF_Request_Portal/ajaxJSON.php
  LEAF_Request_Portal/api/controllers/FormController.php
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/sources/Form.php
Labels: With QA

#2615 LEAF 4455 metadata and userMetadata reading
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/View.php
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  LEAF_Request_Portal/templates/view_status.tpl
Labels: rc-ready

#2620 Revert - Merge pull request #2615 (leaf-4455)
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/View.php
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  LEAF_Request_Portal/templates/view_status.tpl
Labels: revert

#2619 LEAF 4597 - move orgchart keyboard info banner
  LEAF_Nexus/css/editor.css
  LEAF_Nexus/js/ui/position.js
  LEAF_Nexus/templates/editor.tpl
Labels: With QA

#2622 LEAF 4455 metadata reading (ao 121224)
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/sources/View.php
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  LEAF_Request_Portal/templates/view_status.tpl
Labels: With QA

#2616 Leaf 4376 - update user name part 2
  app/Leaf/VAMCActiveDirectory.php
  scripts/scheduled-task-commands/disableNationalOrgchartEmployees.php
  scripts/scheduled-task-commands/updateNationalOrgchartEmployees.php
  scripts/updateNationalOrgchart.php
Labels: With QA
