Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-02, with the labels that each got.

#2273 LEAF 4169 IFTHEN - new controllers and operators
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.css
  LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/print_form.tpl
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/dialog_content/ConditionsEditorDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormatPreview.js
Labels: With QA

#2282 LEAF 4047 email addresses in to cc, LEAF 4126 multioption list formatting
  LEAF_Request_Portal/admin/css/mod_templates_email.css
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA

#2288 LEAF 4231 increase chosen width to 100%
  LEAF_Request_Portal/templates/print_form.tpl
Labels: With QA

#2286 LEAF 4196 update file paths for combined inbox
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: With QA

#2285 Leaf 4204 - Setting the 404 on decommissioned sites
  app/Leaf/Site.php
  app/libs/loaders/Leaf_autoloader.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023100500-2024022900.sql
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024022900-2024022901.sql
Labels: enhancement, With QA

#2300 LEAF 4245 orgchart dbupdate file name and dbversion ref
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2020011000-2020062600.sql
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2020062600-2023092100.sql
Labels: rc-ready

#2298 Leaf 4250 - Simplify group/service management in Request Portals
  LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/api/controllers/GroupController.php
  LEAF_Request_Portal/api/controllers/ServiceController.php
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/Service.php
Labels: rc-ready

#2294 LEAF 2938 log form falsey value updates
  LEAF_Request_Portal/sources/FormEditor.php
Labels: rc-ready

#2292 LEAF 4234 portal menu home 508 adjustments
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/js/formSearchMultisite.js
  LEAF_Request_Portal/templates/initial_form.tpl
  LEAF_Request_Portal/templates/menu.tpl
  LEAF_Request_Portal/templates/menu_help.tpl
  LEAF_Request_Portal/templates/menu_links.tpl
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/view_search.tpl
  app/libs/js/LEAF/formSearch.js
  libs/js/LEAF/formSearch.js
Labels: rc-ready

#2290 LEAF 4233 fix null service name
  LEAF_Request_Portal/sources/Service.php
Labels: rc-ready

#2289 LEAF-4242 -Fix typo
  app/libs/css/leaf.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  docker/vue-app/src/form_editor/components/FormBrowser.js
Labels: rc-ready

#2287 LEAF 4223 idea inbox customizations
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.css
  LEAF_Request_Portal/js/combined_inbox_editor/src/combined_inbox_editor.vue.js
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready
