Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-01, with the labels that each got.

#2262 LEAF 4190 fix eye icon url
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2265 LEAF 4193 - add relative position to parent to prevent form shift
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2269 LEAF 4194 - workflow requirement related logging
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/api/controllers/WorkflowController.php
  LEAF_Request_Portal/sources/Workflow.php
  app/Leaf/Logger/DataActionLogger.php
  app/Leaf/Logger/Formatters/DependencyFormatter.php
  app/Leaf/Logger/Formatters/WorkflowFormatter.php
  app/Leaf/Logger/LogFormatter.php
Labels: With QA

#2261 LEAF-4198 - CodeQL remediation
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/gridInput.js
Labels: rc-ready, With QA

#2270 Leaf 4207 - Add missing dialog template
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready

#2271 Leaf 4208 - Resolve issue related to incorrect "custom" designation
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/api/controllers/EmailTemplateController.php
  LEAF_Request_Portal/api/controllers/TemplateController.php
  LEAF_Request_Portal/sources/EmailTemplate.php
  LEAF_Request_Portal/sources/Template.php
Labels: rc-ready, With QA

#2258 LEAF-4197 - Cleanup
  LEAF_Request_Portal/js/formQuery.js
  LEAF_Request_Portal/report.php
  LEAF_Request_Portal/templates/reports/coach_roster.tpl
  app/libs/js/LEAF/WARNING.md
  app/libs/js/LEAF/formQuery.js
  app/libs/js/LEAF/formSearch.js
  app/libs/js/portal/model/FormQuery.js
  docker/mysql/db/boilerplate/orgchart_boilerplate_empty.sql
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
  libs/jsapi/portal/model/FormQuery.js
Labels: rc-ready, With QA

#2263 LEAF-4199 - Text updates
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready, With QA

#2264 LEAF-4200 - Fix default Inbox columns
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready, With QA

#2277 Leaf 4210 - former backups cant be removed from system admin
  LEAF_Request_Portal/sources/Group.php
  LEAF_Request_Portal/sources/System.php
Labels: bug

#2281 LEAF-4214 - Attempt to fix html scrubber
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: hotfix, With QA

#2276 LEAF 4195 add files to legacy inbox view
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/templates/view_inbox.tpl
Labels: With QA
