Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-05, with the labels that each got.

#2386 LEAF 4339 Admin UX
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/sources/Form.php
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/components/CategoryItem.js
  docker/vue-app/src/form_editor/components/IndicatorPrivileges.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  x-test/API-tests/form.go
  x-test/API-tests/form_test.go
Labels: With QA

#2382 LEAF-4335 Resolve issues with integrated forms
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/Workflow.php
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: With QA

#2377 LEAF 4311, LEAF 4330 formGrid 508 no buttons and DOM scrub
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
Labels: With QA

#2376 LEAF 4331 remove codemirror style sizer override
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
Labels: With QA

#2384 LEAF 4336 Add Indicator for Special Access Restrictions in the Form Editor
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormIndexListing.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
Labels: With QA

#2369 LEAF 4315 checkpoint date headers edgecase
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2394 LEAF 4342 fix comment note overflow
  LEAF_Request_Portal/css/style.css
Labels: With QA

#2390 LEAF-4343 - Form workflow error handling
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/js/workflow.js
  LEAF_Request_Portal/sources/FormWorkflow.php
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/dbsetup_test.go
  x-test/API-tests/employee_test.go
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/formStack_test.go
  x-test/API-tests/formWorkflow_test.go
  x-test/API-tests/form_test.go
  x-test/API-tests/hotspot_benchmarks_test.go
  x-test/API-tests/main_test.go
  x-test/API-tests/service_test.go
Labels: With QA

#2395 LEAF-4346 - formSearch.js cleanup
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2399 LEAF 4238 update print to PDF homeurl
  LEAF_Request_Portal/js/formPrint.js
Labels: rc-ready

#2408 LEAF-4359 - Avoid duplicate message in formGrid
  LEAF_Request_Portal/js/formGrid.js
Labels: rc-ready

#2410 LEAF-4361 - Use CSS position: sticky in formGrid headers
  LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  app/libs/js/LEAF/formGrid.js
  docker/vue-app/src/site_designer/LEAF_Designer.scss
  libs/js/LEAF/formGrid.js
Labels: rc-ready

#2402 LEAF-4351 - Form Editor: Fix access indicator
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2401 LEAF-4350 - Report Builder: Only join service when requested
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2411 LEAF 4232 subordinate site warning when primary changed
  LEAF_Request_Portal/admin/templates/mod_system.tpl
Labels: rc-ready

#2409 LEAF-4360 - Revert inbox role organization
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: rc-ready

#2400 LEAF 4344 - add metadata column to portal data, data_history
  LEAF_Request_Portal/sources/Form.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024022901-2024052000.sql
Labels: database, rc-ready

#2416 LEAF-4364 - INC33016631 Data export date not detected as date
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
Labels: With QA

#2398 LEAF-4349 - Query step actions
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/view_search.tpl
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/form_test.go
Labels: With QA

#2413 LEAF 4362 Add word breaks for form comments and content
  LEAF_Request_Portal/css/style.css
  LEAF_Request_Portal/js/workflow.js
Labels: rc-ready

#2391 LEAF 4289 - form print view orgchart employee
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: With QA
