Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-03, with the labels that each got.

#2299 LEAF 4248 update availability for variable used for uploads
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: hotfix, With QA

#2307 LEAF 4259 - set browsertype span to 11px, rm table font change
  LEAF_Request_Portal/css/style.css
Labels: With QA

#2302 Leaf 4251 - Update email subject text
  LEAF_Request_Portal/templates/email/LEAF_automated_reminder_subject.tpl
  LEAF_Request_Portal/templates/email/LEAF_mass_action_remind_subject.tpl
  LEAF_Request_Portal/templates/email/LEAF_notify_next_subject.tpl
  LEAF_Request_Portal/templates/email/LEAF_send_back_subject.tpl
Labels: With QA

#2296 Leaf 4216 - fixes large number exports.
  LEAF_Request_Portal/js/formGrid.js
Labels: enhancement, With QA

#2295 LEAF-4241 - INC31179685 : Mail error No Recipients
  LEAF_Request_Portal/sources/Email.php
Labels: bug, With QA

#2293 Leaf 4239 - cleanup after 4204 release
  app/Leaf/Site.php
Labels: With QA

#2315 Leaf 4260 - service headings now show correctly
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
Labels: bug, With QA

#2309 LEAF 4229 form editor v2 updates, round 3
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js.LICENSE.txt
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.css
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js.LICENSE.txt
  docker/vue-app/src/common/LEAF_Vue_Dialog__Common.scss
  docker/vue-app/src/common/components/LeafFormDialog.js
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/BrowserMenu.js
  docker/vue-app/src/form_editor/components/CategoryItem.js
  docker/vue-app/src/form_editor/components/GridCell.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/EditPropertiesPanel.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormEditorMenu.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormIndexListing.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/router/index.js
  docker/vue-app/src/form_editor/views/FormBrowserView.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  docker/vue-app/src/form_editor/views/RestoreFieldsView.js
  docker/vue-app/webpack.config.js
Labels: With QA

#2305 LEAF-4256 - PHP Warning Undefined array key
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
Labels: bug, With QA

#2323 Rc/2024 03 12/sprint 69 c3
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/sources/Service.php
  LEAF_Request_Portal/sources/System.php
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js.LICENSE.txt
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.css
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js.LICENSE.txt
  docker/vue-app/src/common/LEAF_Vue_Dialog__Common.scss
  docker/vue-app/src/common/components/LeafFormDialog.js
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/BrowserMenu.js
  docker/vue-app/src/form_editor/components/CategoryItem.js
  docker/vue-app/src/form_editor/components/GridCell.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/StapleFormDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/EditPropertiesPanel.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormEditorMenu.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormIndexListing.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/router/index.js
  docker/vue-app/src/form_editor/views/FormBrowserView.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  docker/vue-app/src/form_editor/views/RestoreFieldsView.js
  docker/vue-app/webpack.config.js
Labels: on-prod, on-preprod

#2320 LEAF 4253 fix file name with spaces
  LEAF_Request_Portal/admin/templates/mod_form.tpl
Labels: on-prod, on-preprod, With QA
