Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-09, with the labels that each got.

#2535 Rc/2024 08 27/sprint 80 c2
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Nexus/sources/Employee.php
  LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024071100-2024082000.sql
  libs/js/LEAF/formGrid.js
  x-test/end2end/playwright.config.ts
  x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
Labels: release

#2536 Leaf 4500 - avoid phantom increments
  x-test/API-tests/employee_test.go
Labels: With QA, automated test

#2518 LEAF 4478 initial formquery orgchart values test
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery.go
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/metadata-types.go
Labels: rc-ready, automated test

#2543 Leaf 4501 - Database update
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2023092100-2024092100 .sql
Labels: database

#2542 LEAF 4476 prevent orgchart selector ID collision
  LEAF_Nexus/js/employeeSelector.js
  LEAF_Nexus/js/groupSelector.js
  LEAF_Nexus/js/positionSelector.js
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: rc-ready

#2541 LEAF 4505 move aria label and address truncation issue
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
  libs/js/LEAF/formGrid.js
Labels: With QA

#2540 Resolve JS error (dev console approval), Improve tests
  LEAF_Request_Portal/admin/templates/site_elements/generic_OkDialog.tpl
  LEAF_Request_Portal/admin/templates/site_elements/generic_confirm_xhrDialog.tpl
  LEAF_Request_Portal/admin/templates/site_elements/generic_simple_xhrDialog.tpl
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/templates/form.tpl
  LEAF_Request_Portal/templates/reports/LEAF_start_leaf_dev_console_request.tpl
  LEAF_Request_Portal/templates/site_elements/generic_OkDialog.tpl
  LEAF_Request_Portal/templates/site_elements/generic_confirm_xhrDialog.tpl
  LEAF_Request_Portal/templates/site_elements/generic_xhrDialog.tpl
  x-test/end2end/README.md
  x-test/end2end/playwright.config.ts
  x-test/end2end/tests/lifecycleDeveloperConsoleApproval.spec.ts
  x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
Labels: automated test

#2539 Leaf 4465 - 508 keyboard navigation updates
  LEAF_Nexus/js/ui/position.js
  LEAF_Nexus/templates/editor.tpl
  LEAF_Nexus/templates/navigator.tpl
Labels: rc-ready

#2548 LEAF 4522 update script for notes, records, data_history fields
  scripts/leaf-scripts/update_records_notes_dh_fields.php
Labels: rc-ready

#2547 LEAF 4507 posting data to new metadata related fields
  LEAF_Nexus/sources/Employee.php
  LEAF_Request_Portal/api/controllers/NotesController.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready
