Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-10, with the labels that each got.

#2559 LEAF 4523 (INC35162350) fix workflow copy step title encoding
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: With QA

#2556 LEAF-4545 Form Library UX and Quicklinks
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/admin/templates/view_form_library.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Start_Request.tpl
Labels: With QA

#2586 LEAF-4580 - Resolve orphaned commit
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2023092100-2024092100.sql
Labels: bug

#2589 Leaf 4564 - liveness probe
  health_checks/index.php
Labels: rc-ready
