Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-06, with the labels that each got.

#2426 LEAF-3895 - Automated Scripts Error Handling
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Request_Portal/scripts/automated_email.php
  app/Leaf/ErrorNotify.php
  docker/php/leaf_monlith.dockerfile
  scripts/scheduled-task-commands/automatedEmailReminder.php
  scripts/scheduled-task-commands/globals.php
  scripts/scheduled-task-commands/refreshOrgchartEmployees.php
Labels: rc-ready

#2423 Leaf 3135 - email priors on cancel
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/email/LEAF_cancel_notification_body.tpl
  LEAF_Request_Portal/templates/email/LEAF_cancel_notification_subject.tpl
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024060200-2024060600.sql
Labels: feature, database, rc-ready

#2420 LEAF 4369 Report Builder stopword issues
  LEAF_Request_Portal/sources/Form.php
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/form_test.go
Labels: rc-ready

#2418 Leaf 4378 - Change wording
  LEAF_Request_Portal/sources/Form.php
Labels: rc-ready

#2425 Leaf 4382 - Switch to descending record index
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024052000-2024060200.sql
Labels: database, With QA

#2422 Leaf 4380 - Filter childkeys
  LEAF_Request_Portal/api/RESTfulResponse.php
  x-test/API-tests/formQuery.go
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/form_test.go
Labels: With QA

#2427 Leaf 4386 - Report Builder: Add example in the JSON dialog
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2447 LEAF 4405 fix warning associated with undefined array key
  LEAF_Request_Portal/sources/Form.php
Labels: With QA

#2446 LEAF 4404 action_history userMetadata portal db upgrade file
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024060700-2024062000.sql
Labels: database, on-prod, on-preprod

#2451 Rc/2024 06 18/sprint 76 c2
  LEAF_Request_Portal/sources/Form.php
  app/Leaf/CommonConfig.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024060700-2024062000.sql
  test/ComplianceScanner/package-lock.json
Labels: on-prod, on-preprod

#2452 LEAF 4357 avoid multiple joins (INC33064668 report not loading)
  LEAF_Request_Portal/js/formSearch.js
  LEAF_Request_Portal/sources/Form.php
Labels: With QA

#2438 Leaf 4398 - Update JS HTML scrubber
  LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Sitemap_Search.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2442 Leaf 4403 - Loading UX
  LEAF_Request_Portal/js/formGrid.js
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: rc-ready

#2435 LEAF 4373 (part1) - posting to data metadata field
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/subindicators.tpl
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery.go
  x-test/API-tests/formQuery_test.go
  x-test/API-tests/metadata-types.go
Labels: With QA

#2449 LEAF 4402 update gridsplitter to use formQuery
  LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
Labels: With QA

#2461 LEAF-4414 getfiles - update param type
  LEAF_Request_Portal/sources/System.php
Labels: hotfix, rc-ready
