Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-08, with the labels that each got.

#2490 LEAF-4461 Optimize hotspot: avoid multiple joins
  LEAF_Request_Portal/sources/Form.php
  x-test/API-tests/formQuery_test.go
Labels: rc-ready

#2493 Leaf 4449 - orgchart refresh plus tests
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  x-test/API-tests/database/portal_test_db.sql
  x-test/API-tests/formQuery_test.go
Labels: enhancement, rc-ready

#2492 LEAF-4460 Improve syntax consistency
  LEAF_Nexus/sources/Employee.php
  LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
Labels: rc-ready

#2498 LEAF 4467 fix step id checking
  LEAF_Request_Portal/sources/Workflow.php
Labels: rc-ready

#2488 LEAF - 4443: script to update prior action_history userMetadata
  scripts/leaf-scripts/update_AH_userMetadata.php
Labels: review/comment only

#2510 Leaf 4438 apostrophes in email subject line
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: rc-ready

#2499 LEAF-4469 (assoc 4463) add customTemplate call for admin menu
  LEAF_Request_Portal/admin/index.php
Labels: rc-ready

#2523 Leaf 4106 - monitor log failures
  LEAF_Request_Portal/mailer/mailer.php
  app/Leaf/ErrorNotify.php
  scripts/scheduled-task-commands/automatedEmailReminder.php
  scripts/scheduled-task-commands/automatedEmailReminderVAPO.php
Labels: rc-ready

#2500 LEAF-4425 prevent built-in email template changes
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/sources/Workflow.php
  x-test/API-tests/events.go
  x-test/API-tests/events_test.go
Labels: rc-ready

#2532 LEAF-4498 - Mitigate dialog button race condition
  LEAF_Request_Portal/admin/templates/site_elements/generic_xhrDialog.tpl
  LEAF_Request_Portal/js/dialogController.js
  x-test/end2end/playwright.config.ts
  x-test/end2end/tests/lifecycleSimpleTravel.spec.ts
Labels: With QA

#2522 Leaf 4474 - prevent phantom increments take2
  LEAF_Nexus/scripts/refreshOrgchartEmployees.php
  LEAF_Nexus/sources/Employee.php
Labels: With QA
