Repository department-of-veterans-affairs/LEAF, pull requests merged in 2024-04, with the labels that each got.

#2335 Leaf 4284 - Add to Nexus button returns
  LEAF_Request_Portal/admin/templates/mod_groups.tpl
Labels: With QA

#2330 LEAF-4241 - INC31179685 - mail error no recipients
  LEAF_Request_Portal/scripts/automated_email.php
  LEAF_Request_Portal/sources/Email.php
  docker/docker-compose.yml
  docker/php/leaf_monlith.dockerfile
  scripts/automatedEmailReminder.php
  scripts/timebracketcmd.php
Labels: bug, With QA

#2329 Leaf 4285 - Data dictionary UX
  LEAF_Request_Portal/templates/reports/LEAF_Data_Dictionary.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2332 LEAF 4283 add cc to tracker history
  LEAF_Request_Portal/sources/Email.php
Labels: With QA

#2326 Leaf 4279 - refactor service chiefs page
  LEAF_Request_Portal/admin/templates/mod_svcChief.tpl
Labels: With QA

#2339 LEAF 4286 service chiefs area member sorting
  LEAF_Request_Portal/sources/Service.php
Labels: With QA

#2333 LEAF 4274 file options natural sorting
  LEAF_Request_Portal/js/form.js
  LEAF_Request_Portal/js/gridInput.js
Labels: With QA

#2352 LEAF 4308 new - use current master formGrid for now
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
Labels: With QA

#2350 LEAF-4294 - site admin clear required field
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: bug, rc-ready

#2343 LEAF 4298 fix callback error in view_position set supervisor
  LEAF_Nexus/templates/view_position.tpl
Labels: rc-ready

#2345 Leaf 4271 - orphaned users and chiefs
  LEAF_Request_Portal/sources/System.php
Labels: rc-ready

#2349 Leaf 4307 - Simple data visualizer
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
Labels: With QA

#2357 LEAF 4299 unrepresented characters in email templates
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA

#2364 LEAF 4318 fix stepinfo submodal popup
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: With QA

#2359 LEAF 4317 add placeholder text to choicesjs multiselect box
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2367 Leaf 2836 - Hide edit buttons inside inbox and open UID link in new tab
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: With QA

#2361 Leaf 4319 - Report Builder: Default option to reduce metadata for JSON exports
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2360 LEAF-4273 - Fix broken QR code
  LEAF_Request_Portal/qrcode/index.php
Labels: With QA

#2355 LEAF 4069 Template Editor updates
  LEAF_Request_Portal/admin/css/mod_templates.css
  LEAF_Request_Portal/admin/css/mod_templates_email.css
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
  LEAF_Request_Portal/admin/templates/mod_templates.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/admin/templates/mod_templates_reports.tpl
  LEAF_Request_Portal/sources/TemplateFileHistory.php
Labels: With QA

#2344 Leaf 4301 - User Experience (Form Editor v2, Report Builder)
  LEAF_Request_Portal/admin/templates/menu.tpl
  LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  LEAF_Request_Portal/templates/view_reports.tpl
  app/libs/css/leaf.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js.LICENSE.txt
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js.LICENSE.txt
  docker/vue-app/package.json
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/FormBrowser.js
  docker/vue-app/src/form_editor/components/dialog_content/EditCollaboratorsDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/ImportFormDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/EditPropertiesPanel.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormEditorMenu.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/views/FormBrowserView.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  docker/vue-app/src/form_editor/views/RestoreFieldsView.js
Labels: With QA

#2375 Form editor UI fixes - Part 2
  LEAF_Request_Portal/admin/index.php
  LEAF_Request_Portal/admin/templates/form_editor_vue.tpl
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  docker/vue-app/src/form_editor/LEAF_FormEditor_App_vue.js
  docker/vue-app/src/form_editor/components/dialog_content/AdvancedOptionsDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/EditPropertiesPanel.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
Labels: rc-ready

#2372 LEAF 4329 - No fuss development environment
  .gitignore
  LEAF_Nexus/sources/Config.php
  LEAF_Request_Portal/sources/Config.php
  docker/docker-compose.yml
  docker/env_files/globals_local_leaf2.env
  docker/mysql/db/boilerplate/resource_database_boilerplate.sql
  docker/mysql/dev_bootstrap.sh
  docker/mysql/dev_db/dev_leaf_portal.sql
  docker/mysql/dev_db/dev_leaf_users.sql
  docker/mysql/dev_db/dev_national_leaf_launchpad.sql
  docker/mysql/leaf_portal.sql
  docker/mysql/my.cnf
  docker/mysql/mysql.dockerfile
  docker/mysql/setup_database.sh
  docker/nginx/leaf_nginx.dockerfile
  docker/php/conf.d/php.ini
  docker/php/dev/phpinfo.php
  docker/php/leaf_monlith.dockerfile
  docs/InstallationConfiguration.md
  favicon.ico
  go.work
  index.html
Labels: rc-ready

#2366 Leaf 4323 - Data Visualizer: Cleanup layout
  LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
Labels: rc-ready

#2334 Leaf 4290 - Development DB environment
  docker/mysql/dev_bootstrap.sh
Labels: rc-ready
