Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-02, with the labels that each got.

#2665 LEAF-4607 - data visualizer display
  LEAF_Request_Portal/templates/reports/LEAF_Data_Visualizer.tpl
Labels: Merge&Test

#2676 LEAF 4667 add cancel button template logic
  LEAF_Request_Portal/templates/print_form.tpl
Labels: Merge&Test, new/update test needed?

#2675 LEAF 4669 required validator reset logic correction
  LEAF_Request_Portal/js/form.js
Labels: Merge&Test, awaiting demo

#2678 Leaf 4670 - nexus indicator update
  docker/mysql/db/db_upgrade/orgchart/Update_OC_DB_2024092100-2025021600.sql
Labels: database, awaiting demo

#2677 LEAF 4615 add textarea for comments when mass action is cancel
  LEAF_Request_Portal/js/pages/mass_action.js
  LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
Labels: awaiting demo, new/update test needed?

#2674 INC37469608 LEAF 4661 catch nexus side export error
  LEAF_Request_Portal/js/formGrid.js
  app/libs/js/LEAF/formGrid.js
Labels: awaiting demo, new/update test needed?

#2671 Leaf 4663 - refactor ad to leaf updates
  LEAF_Nexus/scripts/updateNationalOrgchart.php
  LEAF_Nexus/sources/Employee.php
  app/Leaf/VAMCActiveDirectory.php
  docker/php/leaf_monlith.dockerfile
  scripts/scheduled-task-commands/disableNationalOrgchartEmployees.php
  scripts/scheduled-task-commands/refreshOrgchartEmps.php
  scripts/scheduled-task-commands/updateNationalOrgchartEmployees.php
Labels: awaiting demo
