Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-05, with the labels that each got.

#2737 LEAF-4810 Form.php: Update error response behavior in doModify()
  LEAF_Request_Portal/sources/Form.php
Labels: With QA

#2738 LEAF-4755 Add "insecure" template variable
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: awaiting demo

#2736 LEAF 4758 remove alternate bolded heading label and move html AO
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2734 LEAF 4801 call grid stop if Create Row is used, move style update
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: Merge&Test, With QA

#2719 LEAF-4754 - INC38542820 - Parallel Processing "Invalid report"
  LEAF_Request_Portal/js/parallelProcessing.js
Labels: Merge&Test, With QA, automated test, HOLD

#2741 LEAF-4820 pkg/form/query: Define types
  pkg/form/query/go.mod
  pkg/form/query/response.go
Labels: Merge&Test

#2739 LEAF-4826 - FormWorkflow: Add optional stepID for action validation
  LEAF_Request_Portal/api/controllers/FormWorkflowController.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA
