Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-09, with the labels that each got.

#2778 LEAF 4892 update Email Template Editor to allow org groups
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA, New/update test needed, Demo Complete

#2790 LEAF-5003 - uriencode double slashes
  LEAF_Request_Portal/js/formQuery.js
Labels: Test Complete, Demo Complete

#2788 LEAF-5000 - Remove docker host hardcode and fix getTags empty array
  LEAF_Nexus/sources/Platform.php
Labels: Merge&Test, Test Complete, Demo Complete

#2787 LEAF-4999 - Control track changes
  LEAF_Request_Portal/sources/Form.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2025041000-2025081400.sql
Labels: database, Merge&Test, No Test Required, Demo Complete

#2806 LEAF-5068 - Improve Dev UX
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/formGrid.js
Labels: awaiting demo, No Test Required
