Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-08, with the labels that each got.

#2774 LEAF 4960 Enable deeper customization of printview templates
  LEAF_Request_Portal/ajaxIndex.php
  LEAF_Request_Portal/templates/print_form_ajax.tpl
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: Merge&Test, Test Complete, Demo Complete

#2779 LEAF 4967 (INC39675288) - Form Editor Advanced Formatter style and local data fix, nav hierarchy adjustment
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.css
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js
  app/libs/js/vue-dest/form_editor/LEAF_FormEditor.js.LICENSE.txt
  app/libs/js/vue-dest/form_editor/form-browser-view.chunk.js
  app/libs/js/vue-dest/form_editor/form-editor-view.chunk.js
  app/libs/js/vue-dest/form_editor/restore-fields-view.chunk.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.css
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js
  app/libs/js/vue-dest/site_designer/LEAF_Designer.js.LICENSE.txt
  docker/vue-app/src/common/LEAF_Vue_Dialog__Common.scss
  docker/vue-app/src/form_editor/LEAF_FormEditor.scss
  docker/vue-app/src/form_editor/components/dialog_content/AdvancedOptionsDialog.js
  docker/vue-app/src/form_editor/components/dialog_content/IndicatorEditingDialog.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormEditorMenu.js
  docker/vue-app/src/form_editor/components/form_editor_view/FormQuestionDisplay.js
  docker/vue-app/src/form_editor/views/FormBrowserView.js
  docker/vue-app/src/form_editor/views/FormEditorView.js
  docker/vue-app/src/form_editor/views/RestoreFieldsView.js
Labels: With QA, New/update test needed, Demo Complete

#2793 Leaf 4789 - SSN Scan
  LEAF_Request_Portal/api/index.php
Labels: awaiting demo
