Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-04, with the labels that each got.

#2706 LEAF-4725 Optimize query used in Inbox: Organize by Roles
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/sources/FormWorkflow.php
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: Merge&Test

#2705 LEAF-4700 - if need to know is enabled, replace request titles in emails with the type of form.
  LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
  LEAF_Request_Portal/sources/Email.php
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: Merge&Test

#2687 LEAF-4720 - Clickable Links in User Content (Variation B)
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/js/portalHelpers.js
  LEAF_Request_Portal/templates/print_form.tpl
  LEAF_Request_Portal/templates/print_subindicators_ajax.tpl
Labels: Merge&Test

#2715 HOTFIX: LEAF-4756 Improve feature parity with the old inbox pt2
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: hotfix

#2721 LEAF-4762 - Inbox: Add option to combine individuals
  LEAF_Request_Portal/index.php
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: Merge&Test, With QA

#2709 LEAF-4731 (dependency for LEAF 4705) add formGrid js file to Form Editor view
  LEAF_Request_Portal/admin/index.php
Labels: Merge&Test

#2710 Leaf 4711 - Mass action: Add "Take Action" feature
  LEAF_Request_Portal/js/pages/mass_action.js
  LEAF_Request_Portal/templates/reports/LEAF_mass_action.tpl
Labels: Merge&Test

#2724 LEAF-4771 - Role-based Inbox: Enable custom columns in specific conditions
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: With QA

#2722 LEAF-4765 - Report Builder: Add undefined check
  LEAF_Request_Portal/templates/view_reports.tpl
Labels: With QA

#2718 LEAF-4770 - Optimization: Use userMetadata instead of individual lookups
  LEAF_Request_Portal/sources/FormWorkflow.php
Labels: With QA

#2717 LEAF-4769 - Add tip in LEAF_Start_Request
  LEAF_Request_Portal/templates/reports/LEAF_Start_Request.tpl
Labels: With QA

#2720 LEAF 4716 - workflow editor UX improvements
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
Labels: With QA

#2727 LEAF-4772 - Resolve page hydration issue
  LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
Labels: With QA
