Repository department-of-veterans-affairs/LEAF, pull requests merged in 2025-01, with the labels that each got.

#2633 LEAF 4543 fix display property on file upload error response
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2630 LEAF 4600 (INC36349916) - email editor CSS update
  LEAF_Request_Portal/admin/css/mod_templates_reports.css
Labels: With QA

#2629 LEAF 4258 orgchart group and position, fix report builder display when not found
  LEAF_Request_Portal/sources/Form.php
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2628 LEAF 4623 address common logged errors (javascript)
  LEAF_Request_Portal/js/dialogController.js
  LEAF_Request_Portal/sources/FormStack.php
  LEAF_Request_Portal/templates/print_subindicators.tpl
  LEAF_Request_Portal/templates/subindicators.tpl
Labels: With QA

#2627 Leaf 4376 missed reference
  scripts/scheduled-task-commands/disableNationalOrgchartEmployees.php
Labels: rc-ready

#2624 Leaf 4486 - prevent user name recycle
  LEAF_Nexus/sources/Employee.php
Labels: With QA

#2641 LEAF 4620 import spreadsheet - new form
  LEAF_Request_Portal/api/controllers/FormEditorController.php
  LEAF_Request_Portal/templates/reports/LEAF_import_data.tpl
  app/libs/js/portal/LEAFPortalAPI.js
Labels: With QA

#2639 Leaf 4630 - update existing disabled user names
  app/Leaf/VAMCActiveDirectory.php
  scripts/scheduled-task-commands/updateExistingDisabledEmployees.php
  scripts/updateExistingDisabledNationalOrgchart.php
Labels: Merge&Test

#2659 LEAF 4625 - history/approval info
  LEAF_Request_Portal/admin/templates/mod_workflow.tpl
  LEAF_Request_Portal/sources/View.php
  LEAF_Request_Portal/sources/Workflow.php
  docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2024112500-2025020100.sql
Labels: database
